### ISSUE TITLE
Add support for Google Cloud Speech API

### ISSUE THREAD

**Issue by BingLingGroup** [BingLingGroup/autosub#10]
[agermanidis/autosub #103](https://github.com/agermanidis/autosub/issues/103)
[agermanidis/autosub #113](https://github.com/agermanidis/autosub/issues/113)
[agermanidis/autosub #86](https://github.com/agermanidis/autosub/issues/86)

**Comment by msongz** [comment]
不知道是否是同类问题
我申请了Google translate 的api key
autosub -i ... -gtv2 A*****avN*****eoOtL*******Ow4
以上用法，有进度条，但最终都提示翻译错误
去掉就成功

**Comment by BingLingGroup** [comment]
@msongz 是同类问题，当前版本未支持cloud speech api

**Comment by BingLingGroup** [comment]
@msongz 好吧才发现你说的是google translate的api，那个我还没试，我等有空试试，可能老客户端库是用不了了，那是以前的人写的代码。
免费的翻译基本上已经够用了，因为是直接来自网页版谷歌翻译，以后可以考虑cloud translation的支持，这个问题主要是写给cloud speech-to-text api的。
你可以另起一个issue关于cloud translation api支持。
