### ISSUE TITLE
错误：错误的API代码。

### ISSUE THREAD

**Issue by Yecgaa1** [BingLingGroup/autosub#101]
E:\autosub_pyinstaller>autosub.exe -S cmn-hans-cn -sapi xfyun -i "C:\同步\ch.mp4" -sconf ".\xfconf.txt"
错误：错误的API代码。

这次可能真的是我的问题，但也找不到

![image](https://user-images.githubusercontent.com/38446391/77891717-f7bfcf80-72a3-11ea-85dd-5a9bd3c3c833.png)

![image](https://user-images.githubusercontent.com/38446391/77891908-4a00f080-72a4-11ea-93f0-d0014da2d048.png)

**Comment by BingLingGroup** [comment]
你需要使用dev分支最新版，而非release里的exe，dev分支的最新版只能使用pip安装，或者你也可以使用这条回复附件里的
[autosub.zip](https://github.com/BingLingGroup/autosub/files/4404304/autosub.zip)
