### ISSUE TITLE
比原版少东西了吧

### ISSUE THREAD

**Issue by peter123123312** [BingLingGroup/autosub#102]
完全无法运行，对比原版少一google文件夹，运行问题提示无法从google.protobf导入模块，克隆安装与下载文件安装问题一样版本0.56alpha与Dev都试了，系统基于debain 的 Kali Linux

**Comment by BingLingGroup** [comment]
google模块的依赖我在setup.py里写了的，就是google-cloud-speech

**Comment by BingLingGroup** [comment]
你先看下你的python版本，按照issue模板填写一下相关信息，我刚才试了，Ubuntu 16 python3.5 pip 20.0.2 安装使用没问题

**Comment by peter123123312** [comment]
谢谢啦，我知道问题了，是我系统多个py thon导致的，挺负责的，还专门回复了我
