### ISSUE TITLE
讯飞动态修正功能

### ISSUE THREAD

**Issue by Yecgaa1** [BingLingGroup/autosub#103]
讯飞存在一个动态修正功能，，可以加强功能，但该接口返回数据不同，需要你程序上的支持

**Comment by BingLingGroup** [comment]
我没研究返回数据，但是目前你可以自己处理数据，用`-of full-src`会输出完整json结果。

**Comment by Yecgaa1** [comment]
所以才说希望你的程序支持这个功能啊。所以才提功能建议啊。
