### ISSUE TITLE
Wrong API code，错误

### ISSUE THREAD

**Issue by lqomg** [BingLingGroup/autosub#105]
**描述问题**
你好，我是用baidu的api执行下列命令出错。
`sudo autosub  -sapi baidu  -sconf config.json -D en -S en  -i YouVideo.mp4 `
`Error: Wrong API code.`
可是在没有-S en参数的时候可以输出字幕文件，但是文件内容都是
`1
00:00:00,440 --> 00:00:06,430

2
00:00:06,440 --> 00:00:09,890

3
00:00:11,100 --> 00:00:17,090

4
00:00:17,100 --> 00:00:23,090`

**期待的行为**
可以输出正确的结果

**操作环境（请提供以下完整数据）：**
- 操作系统: ubuntu
- Python版本: Python 2.7
- Autosub版本: 最新版本

**Comment by BingLingGroup** [comment]
1. 没有指定源语言的话当然只输出时间轴(本地处理的)，是正常功能
2. 只有autosub的dev分支最新版支持baidu api，你可能使用的是alpha版，而且dev分支最新版只支持python 3.5及以上

**Comment by lqomg** [comment]
> 1. 没有指定源语言的话当然只输出时间轴(本地处理的)，是正常功能
> 2. 只有autosub的dev分支最新版支持baidu api，你可能使用的是alpha版，而且dev分支最新版只支持python 3.5及以上

我试了，python用的3.6版本，使用dev最新版本也安装成功，但是依旧报错
出现以下错误：
![微信截图_20200405114632](https://user-images.githubusercontent.com/29908531/78466416-764cbf00-7733-11ea-8f5c-b160ddecdc80.png)

**Comment by BingLingGroup** [comment]
错误信息提示升级一下setuptools，那你升级一下，`pip install setuptools --upgrade`

**Comment by BingLingGroup** [comment]
太长时间没回复，先关了，关闭后仍可回复

**Comment by lqomg** [comment]
忘记回复了，已经解决了呢，谢谢

**Comment by vootshiclone** [comment]
Using 0.5.5-alpha 

If I do this:
autosub -sapi baidu -i /mnt/e/youtube/1.mp4 -sconf /mnt/e/youtube/config.json -S EN  

Getting Error: Wrong API code. 


If I do this:
autosub -sapi baidu -i /mnt/e/youtube/1.mp4 -sconf /mnt/e/youtube/config.json

Stucks on Auditok and then gives the empty .srt

What am I doing wrong?

**Comment by vootshiclone** [comment]
> Forgot to reply, it has been resolved, thank you

What is the solution?

**Comment by BingLingGroup** [comment]
Just update to the latest version first. @vootshiclone
