### ISSUE TITLE
我是mac, 貌似我环境是py3, 直接报错了

### ISSUE THREAD

**Issue by zszen** [BingLingGroup/autosub#110]
**描述问题**
直接调用autosub会出现 “print "The given file does not exist: {0}".format(filename)” 这个我知道是py2的写法
我习惯用pip3 install 结果uninstall删不干净, 再用pip install 貌似还是会报错

**复现问题**
每次terminal输入autosub出现, 用任何命令都这样

**操作环境（请提供以下完整数据）：**

- 操作系统: mac
- Python版本: 3.7.3
- Autosub版本: 0.5.6-alpha

**额外信息**（可选）
无

**Comment by BingLingGroup** [comment]
我没有macOS环境，无法复现……建议查下环境变量

**Comment by BingLingGroup** [comment]
太长时间没有回复，先关了，关闭后仍可回复
