### ISSUE TITLE
语言代码设置 zh/zh-cn 字幕文件出来是粤语

### ISSUE THREAD

**Issue by Benature** [BingLingGroup/autosub#112]
**描述问题**
语言代码设置 zh/zh-cn 字幕文件出来是粤语

**复现问题**
复现问题的步骤:

```shell
autosub -i "16.mp4" -S zh-cn -D zh-cn
autosub -i "16.mp4" -S zh-cn
autosub -i "16.mp4" -S zh -D zh
autosub -i "16.mp4" -S zh
```

以上都试过

**期待的行为**

我需要普通话字幕，得到的字幕文件内容部分如下

```
275
00:14:04,100 --> 00:14:07,140
雖然我唔知你著佢話即係咁多
```

得到的是粤语

**操作环境（请提供以下完整数据）：**

- 操作系统:  mac
- Python版本: 3.7
- Autosub版本: alpha/dev 分支都试过

**Comment by BingLingGroup** [comment]
说明你是香港IP（笑）
在readme和原仓库都说过这个问题，是谷歌的问题，已知且无法解决，规避方法是使用内置的`-bm all`来进行匹配，这样来使用精确的语言代码——至少对于谷歌而言是精确的
https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#语音转文字翻译语言支持

>尽管你可以输入任何你想输入的语言代码，需要指出的是如果你使用了不在清单上的语言代码但是API接受了，[Google-Speech-v2](https://github.com/gillesdemey/google-speech-v2)可能会按照你的IP地址机型个性化识别，而这是不受你控制的。这是一个已知的问题，我已经在原仓库申请了[拉取请求](https://github.com/agermanidis/autosub/pull/136)。
