### ISSUE TITLE
讯飞语音识别语言错误

### ISSUE THREAD

**Issue by ghost** [BingLingGroup/autosub#117]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
识别日语时有时会出现大段识别成中午与英文，只识别中文有时也会出现英文

**复现问题**
复现问题的步骤:

似乎是随机出现的，未找到复现方法，两次完全相同的识别也可能会一次正常一次出现错误

**期待的行为**

按目标语言识别

**截图**
![7d05b1b3db5af659](https://user-images.githubusercontent.com/60865423/81490988-2e353500-92bb-11ea-8164-6673540ffd9c.png)

**操作环境（请提供以下完整数据）：**

- 操作系统: window10
- Python版本: 3.7.0
- Autosub版本: autosub-0.5.7-alpha-pyinstaller

**Comment by BingLingGroup** [comment]
readme里忘了说，日语需要用小语种接口，小语种接口意味着要用不同的地址，根据官方文档，需要把网址改成 `iat-niche-api.xfyun.cn`。目前config文件是支持自定义小语种网址的，你需要在配置文件中如此添加

```json
    "api_address": "iat-niche-api.xfyun.cn",
```

即可，程序会自动读取这个`api_address`的值的。

另外我不太清楚讯飞对日语识别的准确率如何，你可以让它与google speech v2的结果进行对比。

**Comment by BingLingGroup** [comment]
太长时间没回复，我先关了，关闭后仍可回复
