### ISSUE TITLE
Is it compatible with windows 7 32 bit? Because in file name it is x64

### ISSUE THREAD

**Issue by Princesipe** [BingLingGroup/autosub#119]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
清晰并准确地描述问题。

**复现问题**
复现问题的步骤:

1. 你使用的命令行参数。
2. 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。推荐使用以下的代码块markdown语法，将代码块复制到\`\`\`和\`\`\`之间即可。

```
```

3. 等等

**期待的行为**
清晰并准确地描述你本想做的事情。

**截图**
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

**操作环境（请提供以下完整数据）：**

- 操作系统: [譬如 windows]
- Python版本: [譬如 Python 2.7]
- Autosub版本: [譬如 0.4.1-alpha或0.5.4-alpha Nuitka windows发布版]

**额外信息**（可选）
任何其他的能描述问题的信息。

**Comment by BingLingGroup** [comment]
The windows release is not compatible with 32-bit windows.
