### ISSUE TITLE
can autosub support two languages in subtitle simultaneously? 

### ISSUE THREAD

**Issue by SunshineVan** [BingLingGroup/autosub#121]
My video/audio's dialogs are mix of English and Chinese (mandarin) to teach child learn both languages.  I would like to have subtitle in both English and Chinese, do not translate one to the other.

Is there a way to get one SRT file which has both English and Chinese subtitles comply to original dialog in auto file?

**Comment by BingLingGroup** [comment]
That depends on the API. If the API doesn't support multi-language recognition, then autosub can't do it.
