### ISSUE TITLE
Issue on windows cmd due to spaces in source path

### ISSUE THREAD

**Issue by SaranSundaresan** [BingLingGroup/autosub#123]
Hi, I encountered the following issue while using autosub on windows cmd due to spaces in the file path. Pls help!

`C:\Users>autosub -S en -D en 'C:\Users\SARAN SUNDARESAN\Downloads\testtranscipt.mp4'

usage: autosub [-h] [-C CONCURRENCY] [-o OUTPUT] [-F FORMAT] [-S SRC_LANGUAGE]
               [-D DST_LANGUAGE] [-K API_KEY] [--list-formats]
               [--list-languages]
               [source_path]
autosub: error: unrecognized arguments: SUNDARESAN\Downloads\testtranscipt.mp4'
`

**Comment by BingLingGroup** [comment]
Please use the issue template to create a new issue. It seems the version you used is not the latest alpha version.
