### ISSUE TITLE
Function from: One-Click EASY with SENDTO in this new autosub.

### ISSUE THREAD

**Issue by Kestrelbr** [BingLingGroup/autosub#124]
How i make this work from previous old autosub to in this new autosub ? , like this example here below:

One-Click EASY with SENDTO.
Create batch by language (JA) AutoSub_Jap.bat and copy to directory SendTo
"shell:sendto"
"%APPDATA%\Microsoft\Windows\SendTo"
AutoSub_English.bat
C:\Python27\python.exe C:\Python27\scripts\autosub_app.py -C 2 -S en -D en %1

I want to use, like this in new autosub because i have to right click on video so cmd run easy. instead of adding each videos manually. 

autosub -i C:\test\Video1.mp4 -S en
autosub -i C:\test\Video2.mp4 -S en 
etc....

**Comment by BingLingGroup** [comment]
It was mentioned in the [readme](https://github.com/BingLingGroup/autosub#batch-processing).
