### ISSUE TITLE
已经删除

### ISSUE THREAD

**Issue by patui** [BingLingGroup/autosub#128]

**Comment by BingLingGroup** [comment]
恕我直言，没必要重复造轮子了，[aegisub](https://github.com/wangqr/Aegisub)就很好用了，也是C++写的，作者开新坑之前没考虑过去改进[aegisub](https://github.com/wangqr/Aegisub)吗？
另外，与本项目无关的issue直接关闭

**Comment by patui** [comment]
以后你就会明白了，aegisub并不适合小白用户；

**Comment by patui** [comment]
同样的我相信你看都没看过我视频的操作模式就开始否定了，
你去看看我时间轴的设计，
字幕软件这块需要用户体验的创性
我不是说aegisub不够好，甚至我依然觉得它是最专业的字幕软件，
可是它不会更新了，它已经停更六年了，
某些操作方式的确不适合小白用户。

我这里不拿自动语音识别这块说，
就单论纯手动打轴这块，
aegisub也需要专业门槛，
而且编辑效率极低，
网上的所谓的高效率都是建立在你熟练使用一段时间aegisub之后，

 就好像你熟练掌握PS，然后再来说PS多简单，这不是耍流氓吗。
