### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by ghost** [BingLingGroup/autosub#136]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
TypeError: cannot unpack non-iterable NoneType object

**To Reproduce**
autosub -i test.mp4 -er "test.times.srt" -sapi gcsv1 -skey [REDACTED] -S de-de -D en

- Command line arguments you are using.Use the following markdown code block syntax is recommended. Copy them into the place between \`\`\`.

```
-sapi gcsv1 -S de-de -D en

I've also tried with -S auto, -sapi gsv2, I've tried not using -er and letting it figure out the regions on its own, it always does the same thing.
```

- A complete copy of command line output of the autosub. You can use `Ctrl-A` and `Ctrl-C` to copy all of them. 

```
autosub -i test.mp4 -er "test.times.srt" -sapi gcsv1 -skey [REDACTED] -S de-de -D en
Use external speech regions.
C:\Program Files\ImageMagick-7.0.10-Q16\ffmpeg.exe -hide_banner -y -i "test.mp4" -vn -ac 1 -ar 16000 -loglevel error "C:\Users\REALDR~1\AppData\Local\Temp\tmpagfbmzk5.wav"

Converting speech regions to short-term fragments.
Converting: 100% |####################################################| Time:  0:00:04 Use the API key given in the option "-skey"/"--speech-key".

Sending short-term fragments to Google Cloud Speech V1P1Beta1 API and getting result.
Speech-to-Text: 100% |################################################| Time:  0:00:34 Traceback (most recent call last):
  File "autosub\__main__.py", line 25, in <module>
  File "autosub\__init__.py", line 159, in main
  File "autosub\cmdline_utils.py", line 1369, in audio_or_video_prcs
TypeError: cannot unpack non-iterable NoneType object
[14460] Failed to execute script __main__
```

- If a config file is used, attach the config file, but be sure to remove any information related to your accounts.

```json
Use this to display your config.
```

- etc.

**Expected behavior**
Transcribe and translate subtitles.

**Screenshots**
If applicable, add screenshots to help explain your problem. But it is not recommended using screenshots to demonstrate the commandline output unless you think it really matters.

**Environment (please complete the following information):**

- OS: [e.g. windows] Windows 10
- Python Version: [e.g. Python 3.7] Python 3.8.3
- Autosub Version: [e.g. 0.4.1-alpha/0.5.4-alpha Nuitka windows release] 0.5.7-alpha

**Additional context** (Optional)

**Comment by BingLingGroup** [comment]
Commit https://github.com/BingLingGroup/autosub/commit/0768a5a4796166d8acd12c80950b5d0fac469621 should fix this. Install the lastest dev version and try again.
