### ISSUE TITLE
为什么遇到不能识别的片段就会中断运行，导致后面的部分不能正常被识别？

### ISSUE THREAD

**Issue by ghGYR** [BingLingGroup/autosub#138]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**

**To Reproduce**

- Command line arguments you are using.Use the following markdown code block syntax is recommended. Copy them into the place between \`\`\`.

```
Use this to display your command line arguments.
```

- A complete copy of command line output of the autosub. You can use `Ctrl-A` and `Ctrl-C` to copy all of them. 

```
Use this to display your output.
```

- If a config file is used, attach the config file, but be sure to remove any information related to your accounts.

```json
Use this to display your config.
```

- etc.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. But it is not recommended using screenshots to demonstrate the commandline output unless you think it really matters.

**Environment (please complete the following information):**

- OS: [e.g. windows]
- Python Version: [e.g. Python 3.7]
- Autosub Version: [e.g. 0.4.1-alpha/0.5.4-alpha Nuitka windows release]

**Additional context** (Optional)

**Comment by BingLingGroup** [comment]
这边建议重新填写issue模板
