### ISSUE TITLE
用默认google api时遇到问题

### ISSUE THREAD

**Issue by Vervinet** [BingLingGroup/autosub#148]
输入了指令autosub -S en-US -i "C:\Users\Vervinet\Desktop\XXX.mp4"没有生成文件，代码运行过程挺正常的，最后却输出了:01:08['{"result":[]}', ''] 不知道怎么回事。有科学上网，用的全局模式
![1](https://user-images.githubusercontent.com/73128765/96480735-37183280-126d-11eb-9456-7881515ad987.png)

**Comment by Vervinet** [comment]
用了-hsp就会有结果 但是结果输出的srt文件识别内容是空的 只有时间轴

**Comment by BingLingGroup** [comment]
刚才检查了一下，疑似api失效，请使用其他支持的api
