### ISSUE TITLE
使用讯飞api产生的问题

### ISSUE THREAD

**Issue by Vervinet** [BingLingGroup/autosub#149]
config.json文件里面必要参数都有填，语言参数是en_us（也试过en-US），然而运行之后却显示没有选择语言
![1](https://user-images.githubusercontent.com/73128765/96602594-c3862c00-1325-11eb-9b83-2785c7432b8f.png)
![1603205166(1)](https://user-images.githubusercontent.com/73128765/96602902-17911080-1326-11eb-9db8-74b95c2b98e0.jpg)

**Comment by BingLingGroup** [comment]
看起来你用的是老版本，请用pip安装仓库内dev分支最新版代码即可解决问题。
新版本发布的话大概要等解决数个微小问题之后才会考虑。
