### ISSUE TITLE
Empty strings in transcription results

### ISSUE THREAD

**Issue by dimqua** [BingLingGroup/autosub#153]
Hello. Each time when I transcribe English-language films I get lots of empty strings in the resulted subtitles. Basically more than half of all dialogues aren't fully transcribed.
I use the following command: `autosub -S en-us -of all -i movie.mkv`
The json file contains lots of emptiness as well:
```
    {
        "start": 72.58,
        "end": 82.57,
        "content": ""
    },
    {
        "start": 82.58,
        "end": 92.57,
        "content": ""
    }
```
I wonder why it may happen, and whether or not I can do something about it? With movies in other languages, I don't have such a problem.

**Comment by BingLingGroup** [comment]
#148 It is suspected that the api is not working. Please use another supported api.
