### ISSUE TITLE
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' 

### ISSUE THREAD

**Issue by zhengzilu** [BingLingGroup/autosub#157]
from google.cloud.speech_v1p1beta1 import enums  # pylint: disable=unused-import
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1p1beta1' 

Enums and Types
WARNING: Breaking change
The submodules enums and types have been removed.

https://github.com/googleapis/python-speech/blob/master/UPGRADING.md#enums-and-types

**Comment by BingLingGroup** [comment]
Duplicated #142
