### ISSUE TITLE
怎么设置 vpn

### ISSUE THREAD

**Issue by nissansz** [BingLingGroup/autosub#162]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
请问一下 vpn怎么设置？
>autosub -S en -i F:\a.wav -hsa https://127.0.0.1:8580
或 autosub -S en -hsa [https://127.0.0.1:8580] -i F:\a.wav

这么运行时报错
用法：autosub [-i 路径] [选项]
autosub: error: unrecognized arguments: https://127.0.0.1:8580

**复现问题**
win10 命令行 运行

- 你使用的命令行参数。推荐使用以下的代码块markdown语法，将代码块复制到\`\`\`和\`\`\`之间即可。

```
使用这个来显示你用来运行的命令行参数。
```

- 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。

```
使用这个来显示你的输出。
```

- 如果使用了config文件，请附上config文件，但注意去掉与账号有关的信息。

```json
使用这个来显示你的config文件。
```

- 等等

**期待的行为**
清晰并准确地描述你本想做的事情。

**截图**
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

**操作环境（请提供以下完整数据）：**

- 操作系统: [譬如windows]
- Python版本: [譬如Python 3.7，但使用发布版(独立运行版)时不用注明]
- Autosub版本: [譬如0.4.1-alpha或0.5.4-alpha Nuitka windows发布版]
win10, python3.8, Autosub-0.5.7-alpha

**额外信息**（可选）
任何其他的能描述问题的信息。

**Comment by BingLingGroup** [comment]
你用错参数了，是`-hsp`不是`-hsa`

**Comment by nissansz** [comment]
好的，谢谢
