### ISSUE TITLE
Cannot type into the terminal after running

### ISSUE THREAD

**Issue by 9mido** [BingLingGroup/autosub#166]
The terminal is stuck after running the autosub command and after seeing "All works done." which should probably say "All work done".

I need to close the terminal with control D to be able to use another command again. Control C does nothing. 

Pressing the Enter key returns the prompt sideways instead of the normal up and down.

**Comment by 9mido** [comment]
@BingLingGroup 

https://github.com/BingLingGroup/autosub/blob/dev/autosub/cmdline_utils.py#L1606-L1610

Adding `os.system('stty sane')` worked.

```
        print(_("Speech language subtitles "
                "file created at \"{}\".").format(subtitles_file_path))

        if not args.output_files:
            os.system('stty sane')
            raise exceptions.AutosubException(_("\nAll works done."))
```

Whatever changes the terminal settings should include a handler to change them back. 

`stty echo` would probably also work.

It's local echo being turned off that causes what you type to not be displayed back to you.

This happens when when a program changes the terminal settings, but doesn't change them back on exit.

**Comment by BingLingGroup** [comment]
Related https://github.com/BingLingGroup/autosub/issues/143#issuecomment-702344721

**Comment by BingLingGroup** [comment]
Commit https://github.com/BingLingGroup/autosub/commit/0d6687831e69195d31d66d503b50113a3939501f should fix this. Thanks for your issue.

**Comment by 9mido** [comment]
@BingLingGroup Yes that change worked. You're welcome and thank you.
