### ISSUE TITLE
Xunfei语音分段切割的逻辑能否优化

### ISSUE THREAD

**Issue by Eli-Thomas** [BingLingGroup/autosub#168]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

我尝试了一个11分钟的语音转文字，autosub回调了165次讯飞语音听写，有点肉疼呀。想问一下现在的语音切分逻辑是什么呢，是否能把语音片段切分模式优化成按分钟组合（尽可能贴近1分钟的方式）？

**Comment by BingLingGroup** [comment]
贴近一分钟的话你还得处理轴啊
目前程序也是支持1分钟的，你调整auditok的参数就可以了，把et调低，mxrs调高不就行了，你去看readme啊
