### ISSUE TITLE
无法解码语音配置文件

### ISSUE THREAD

**Issue by yaojingzhe** [BingLingGroup/autosub#171]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
我试图用百度语音接口把音频转字幕，命令行：
 .\autosub -sapi baidu -i "c:\temp\audio01.wav" -sconf baidu_config.json

出现“无法解码语音配置文件”

配置文件如下：
[baidu_config.zip](https://github.com/BingLingGroup/autosub/files/6316627/baidu_config.zip)

能不能帮我看看，我的配置文件有什么问题，非常感谢

**操作环境：autosub-0.5.7-alpha-win-x64-pyinstaller在win10下，shift+鼠标右键，PowerShell内运行。

- 操作系统: windows 10 1809
- Python版本: 
- Autosub版本:autosub-0.5.7-alpha-win-x64-pyinstaller

**Comment by BingLingGroup** [comment]
你的配置文件位置放对了吗？确定是在和autosub处在同一个目录下面吗？

**Comment by yaojingzhe** [comment]
是的，肯定与autosub.exe在同一目录里，请问，我的配置文件写对了没有？我是用Notepad++写的
请问我的配置文件里，是否还缺少什么，我把你发布的配置文件写法的内容，只是添加了我的appid和2个key
我刚才又试了一次，还是显示“错误：无法解码语音配置文件"baidu_config.json”

**Comment by BingLingGroup** [comment]
你的配置文件是utf-8编码吗？

**Comment by yaojingzhe** [comment]
我是打开Notepad++，选择新建，把您写的复制到Notepad++里，添加app id，aip key和secret key。另存为时，文件类型选“JSON fille(*.josn)”，刚才看了一下是使用UTF-8编码。非常感谢您的回复和帮助。

**Comment by yaojingzhe** [comment]
能不能请您打开我的baidu_config.json文件，看看是否正确，能不能请您帮我编写一个正确的配置文件。

**Comment by BingLingGroup** [comment]
https://github.com/BingLingGroup/autosub/blob/dev/autosub/cmdline_utils.py#L254 decode error只会出现在这个位置，实际上也就是json文件无法解析/解码的情况。

另外我又仔细看了下，你这个json文件写的确实有问题，第十行`1537`后面没有加逗号，这是语法错误。我建议你使用vscode打开&编辑json文件，vscode会显示出有语法错误的地方。

**Comment by yaojingzhe** [comment]
非常感谢您的回复，我已经按照您的方法，解决问题了


再次感谢！













在 2021-04-18 15:49:53，"BingLingGroup" ***@***.***> 写道：

https://github.com/BingLingGroup/autosub/blob/dev/autosub/cmdline_utils.py#L254 decode error只会出现在这个位置，实际上也就是json文件无法解析/解码的情况。

另外我又仔细看了下，你这个json文件写的确实有问题，第十行1537后面没有加逗号，这是语法错误。我建议你使用vscode打开&编辑json文件，vscode会显示出有语法错误的地方。
