### ISSUE TITLE
建议将dev的requirements的google speech尽快合并到alpha分支上去

### ISSUE THREAD

**Issue by pangyouzhen** [BingLingGroup/autosub#173]
看文档alpha默认是稳定分支,按照现在的alpha分支中的requirements ,会报enum的错误,限定后就OK了, 改动不大,但是可以避免别人再去提问

**Comment by BingLingGroup** [comment]
下一个alpha版本功能开发尚未让我满意，同时由于最近时间不多，所以合并暂时搁置。
