### ISSUE TITLE
使用srt给音频分片的时候报错“错误：转换失败。”

### ISSUE THREAD

**Issue by InstantComet** [BingLingGroup/autosub#175]
![屏幕截图 2021-06-22 103947](https://user-images.githubusercontent.com/10364622/122854396-41cc1f80-d346-11eb-9174-5c913daf5256.png)
如图，进图条走完后报告“错误：转换失败。”
使用的版本是0.5.7 pyinstaller版本

**Comment by InstantComet** [comment]
使用的命令是：
.\autosub -i D:\A_UE4CPP\audio_temp_001.flac -ap s -er D:\A_UE4CPP\audio_temp_001.times.srt

**Comment by BingLingGroup** [comment]
Duplicated #122
