### ISSUE TITLE
Dependency error in alpha version (google-cloud-speech not working please use 1.3.1 version) 

### ISSUE THREAD

**Issue by RaihanEXE99** [BingLingGroup/autosub#179]
Dependency error because of google-cloud-speech
Use google-cloud-speech==1.3.1 this will fix the issue in alpha version

Tested on : win , deb , ubuntu 

Error Screenshot
![error](https://user-images.githubusercontent.com/62661424/126048693-bc986140-669e-4673-91d3-d3af00edc182.png)

**Comment by BingLingGroup** [comment]
Duplicated #142
