### ISSUE TITLE
Google Cloud Speech-to-Text API failed with totalBilledTime": "15s"

### ISSUE THREAD

**Issue by ysun** [BingLingGroup/autosub#182]
从autosub最开始的项目找过来。非常棒，一会儿就搞定，生成了字幕。

后来想尝试下gcsv1，刚刚创建了Google cloud账号，enable了cloud speech。
遗憾的是，使用gcsv1时报错了，说：
"totalBilledTime": "15s"

Sending short-term fragments to Google Cloud Speech V1P1Beta1 API and getting result.
Speech-to-Text: 100% |##############################################################################################################################################################| Time:  0:00:05
Receive something unexpected:
{
    "totalBilledTime": "15s"
}
Error: Speech-to-text failed.
All work done.

确认了下，Google console的请求数目是增加的。
![image](https://user-images.githubusercontent.com/1448148/132285804-93f672d9-c357-448a-8bee-b60922167397.png)

是我哪里没有配置对吗？命令行如下：
autosub -i ./test_translate.mp4 -S en-us -hsp https://xxxx:913 -hp http://xxxx:913 -sapi gcsv1 -skey xxxxxx
从准确度来说 gsv2 和 gcsv1那个更好一点？

再次感谢维护这么好的项目！

**Comment by BingLingGroup** [comment]
应该是gcsv1更好。
我觉得可能是因为api更新了，没有做好适配，但我还没进行测试。

相关：#142

**Comment by ysun** [comment]
> 应该是gcsv1更好。
> 我觉得可能是因为api更新了，没有做好适配，但我还没进行测试。

嗯，看着那个返回，不像是错误response，下午还搜到Google的说明。好吧，我有空也看下。如果你们有相应的更新，也这里通知我下，感谢。其实，我还不确定如何更新。
可以给这个issue价格标签 feature request 或者bug。 ：）
