### ISSUE TITLE
where are app_id,api_secret and app_key fields?

### ISSUE THREAD

**Issue by gtoto007** [BingLingGroup/autosub#193]
I want to custom speech-config.json file to introduce the parameter `enable_word_time_offsets`
```
{
    "enable_word_time_offsets": true,
    "language_code": "en",
    "app_id": "***",
    "api_secret": "***",
    "api_key": "***"
}
```
but I didn't found the `app_id`, `api_secret`  and `api_key` in cloud google platform. I can only generate the `api_key`. Where can I find these information?

**Comment by BingLingGroup** [comment]
#142
