### ISSUE TITLE
tmp/tmp{file_name}.flac not getting deleted automatically leading to eventually filling of the storage

### ISSUE THREAD

**Issue by chirag127** [BingLingGroup/autosub#194]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Describe the bug**
tmp/tmp{file_name}.flac not getting deleted automatically leading to eventually filling of the storage
**To Reproduce**

1. run autosub on any video
2. check the files
3.

**Comment by BingLingGroup** [comment]
Please submit the issue according to the issue template.
