### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by sc30zhw** [BingLingGroup/autosub#196]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
翻译视频文件时报错。

**复现问题**
复现问题的步骤:

- 你使用的命令行参数。推荐使用以下的代码块markdown语法，将代码块复制到\`\`\`和\`\`\`之间即可。

```
autosub -i "E:\test.mp4" -S en -D zh-cn。
```

- 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。

```
Traceback (most recent call last):
  File "autosub\__main__.py", line 25, in <module>
  File "autosub\__init__.py", line 159, in main
  File "autosub\cmdline_utils.py", line 1369, in audio_or_video_prcs
TypeError: cannot unpack non-iterable NoneType object
[12520] Failed to execute script __main__
```

- 如果使用了config文件，请附上config文件，但注意去掉与账号有关的信息。

```json
使用这个来显示你的config文件。
```

- 等等

**期待的行为**
希望将测试视频翻译成中文。

**截图**
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

**操作环境（请提供以下完整数据）：**

- 操作系统:windows
- Python版本: py3.9
- Autosub版本: autosub-0.5.7-alpha-win-x64-pyinstaller

**额外信息**（可选）
在使用autosub-0.5.7-alpha-win-x64-nuitka版本时也出现了相同的问题，其提示是TypeError: 'NoneType' object is not iterable，我也找到了在已关闭issue里有一个类似问题#130，但是并未看到解决方案。

**Comment by BingLingGroup** [comment]
请用pip安装使用dev分支最新版

**Comment by BingLingGroup** [comment]
Dupilcated #136
