### ISSUE TITLE
IndexError in list_to_googletrans

### ISSUE THREAD

**Issue by kumaranjeya** [BingLingGroup/autosub#48]
```
Translating text from "zh-cn" to "en".
Translation:   2% |##                                                                                  | ETA:   0:01:08Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\autosub.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 142, in main
    no_audio_prcs=no_audio_prcs)
  File "c:\python27\lib\site-packages\autosub\cmdline_utils.py", line 1015, in audio_or_video_prcs
    service_urls=args.service_urls
  File "c:\python27\lib\site-packages\autosub\core.py", line 306, in list_to_googletrans
    result_list[valid_index[j] - last_index])
IndexError: list index out of range
```

**Comment by BingLingGroup** [comment]
Need to refactor the core.py immediately.

**Comment by BingLingGroup** [comment]
Are you using the latest version 0.5.1a ?

**Comment by kumaranjeya** [comment]
Hi, Yes. I'm using latest version 0.5.1a. 
FYI, I'm also getting similar error when tried translating Translating text from "pt" to "en".

```
Translating text from "pt" to "en".
Translation:   1% |#                                                                                   | ETA:   0:02:39Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\autosub.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 150, in main
    styles_list=None)
  File "c:\python27\lib\site-packages\autosub\cmdline_utils.py", line 631, in subs_trans
    service_urls=args.service_urls
  File "c:\python27\lib\site-packages\autosub\core.py", line 306, in list_to_googletrans
    result_list[valid_index[j] - last_index])
IndexError: list index out of range
```

**Comment by BingLingGroup** [comment]
> Hi, Yes. I'm using latest version 0.5.1a.
> FYI, I'm also getting similar error when tried translating Translating text from "pt" to "en".
> 
> Translating text from "pt" to "en".
> Translation: 1% |# | ETA: 0:02:39Traceback (most recent call last):
> File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main "**main**", fname, loader, pkg_name) File "c:\python27\lib\runpy.py", line 72, in _run_code exec code in run_globals File "C:\Python27\Scripts\autosub.exe__main__.py", line 9, in File "c:\python27\lib\site-packages\autosub__init__.py", line 150, in main
> styles_list=None)
> File "c:\python27\lib\site-packages\autosub\cmdline_utils.py", line 631, in subs_trans
> service_urls=args.service_urls
> File "c:\python27\lib\site-packages\autosub\core.py", line 306, in list_to_googletrans
> result_list[valid_index[j] - last_index])
> IndexError: list index out of range

@kumaranjeya It's nothing to do with the language. Its just a logical bug. I will fix it in no time.

**Comment by BingLingGroup** [comment]
> Hi, Yes. I'm using latest version 0.5.1a.
> FYI, I'm also getting similar error when tried translating Translating text from "pt" to "en".
> 
> ```
> Translating text from "pt" to "en".
> Translation:   1% |#                                                                                   | ETA:   0:02:39Traceback (most recent call last):
>   File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "c:\python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Python27\Scripts\autosub.exe\__main__.py", line 9, in <module>
>   File "c:\python27\lib\site-packages\autosub\__init__.py", line 150, in main
>     styles_list=None)
>   File "c:\python27\lib\site-packages\autosub\cmdline_utils.py", line 631, in subs_trans
>     service_urls=args.service_urls
>   File "c:\python27\lib\site-packages\autosub\core.py", line 306, in list_to_googletrans
>     result_list[valid_index[j] - last_index])
> IndexError: list index out of range
> ```

[Commit 3da6285](https://github.com/BingLingGroup/autosub/commit/3da6285c4c1acaf3803fdd680ef7775eb0c39fa5) should fix this issue. Thanks for your feedback.
