### ISSUE TITLE
Flac output processing taking too long

### ISSUE THREAD

**Issue by kumaranjeya** [BingLingGroup/autosub#50]
Hi, just curious why the flac processing taking too long? Is this normal? Example, if an video file 1hour long, the flac output processing also taking 1 hour too. Is it possible to make it faster? Previously, if I'm not mistaken in v0.5.0-alpha it was faster. Please advise. Below is the flac output process.

```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
  Stream #0:1 -> #0:1 (aac (native) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 000001e49e5874c0] encoding as 24 bits-per-sample2:22.77 bitrate=  -0.0kbits/s speed=N/A
[flac @ 000001e49e3db000] Video stream #0 is not an attached picture. Ignoring
Output #0, flac, to 'c:\users\akumar~1\appdata\local\temp\tmpxt7xdo.flac':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: png, rgb24(progressive), 1152x720 [SAR 1:1 DAR 8:5], q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2018-03-04T02:27:29.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/03/2018.
      encoder         : Lavc58.35.100 png
    Stream #0:1(und): Audio: flac, 44100 Hz, mono, s32 (24 bit), 128 kb/s (default)
    Metadata:
      creation_time   : 2018-03-04T02:27:29.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 03/03/2018.
      encoder         : Lavc58.35.100 flac
frame=20630 fps= 10 q=-0.0 size=   52992kB time=00:11:27.54 bitrate= 631.4kbits/s speed=0.332x
```

**Comment by BingLingGroup** [comment]
You can check the [diff](https://github.com/BingLingGroup/autosub/compare/BingLingGroup:0.5.0-alpha...dev?diff=split&short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) between the latest and the 0.5.0-alpha. There's no significant change on flac conversion.

**Comment by BingLingGroup** [comment]
Also, if you are not satisfied with the current conversion command, you can manually replace it by using `-acc`/`--audio-conversion-cmd`.

Apart from that, you can also do the conversion outside the autosub. You can manually input `-ap n` to override the conversion.

**Comment by BingLingGroup** [comment]
I think it's OK to close this issue.

**Comment by BingLingGroup** [comment]
I think it's OK to close this issue.

**Comment by kumaranjeya** [comment]
Hi, noted. Thank you for quick reply.
