### ISSUE TITLE
music video/song subtitling

### ISSUE THREAD

**Issue by brcisna** [BingLingGroup/autosub#53]
Hello All,

This is really not an autosub deficiency, but curious if it is at all possible to autosub a video song. Have tried all of the online subtitling products and none work either.
Am guessing with the background music with various instruments trying to get anywhere close to correct subtitlng will be impossible.

Thank You.

**Comment by BingLingGroup** [comment]
You can use some audio processing softwares like Adobe Audition to filter out the background music. Then leave it to autosub.
Or use the built-in [audio pre-processing](https://github.com/BingLingGroup/autosub#input) function, though it may not work that well.

**Comment by brcisna** [comment]
Hello BLG,

Thank you for the suggestion(s). This gave me a thought and was able to use Audacity, with the 'noise reduction' feature. After playing around with the settings was able to get a couple songs background gone to were the singer sounded to be singing acapela. Unfortunately, google translate only got about 4 words out of each song i remixed. with 0 background noise I think what happens is,,when being sung the words are so drawn out they are not interpreted correctly?

Thank You

**Comment by BingLingGroup** [comment]
@brcisna Perhaps you are right. That's the api's problem.

**Comment by BingLingGroup** [comment]
I guess it's OK to close this issue.
