### ISSUE TITLE
windows Python 3 release usage

### ISSUE THREAD

**Issue by D170302066** [BingLingGroup/autosub#55]

**Comment by D170302066** [comment]
您好，程序小白，但又非常想在python3 下，win10x64环境使用autosub，请您指导一下如何使用您的release？感谢！

**Comment by BingLingGroup** [comment]
[中文版readme](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#在windows上安装)里面已经写得很清楚了，关于release的使用。

以及一些[典型用法](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#典型用法)。

我觉得可以关闭这个问题了，都是readme里面的东西。

**Comment by D170302066** [comment]
Filename SHA256
autosub-0.5.1-alpha-win-x64-pyinstaller.7z 33bebf34627a73d528030d06fdc119be538b27055c317a38fe9b45c67ea641e0
autosub-0.5.1-alpha-win-x64.7z f73c6e82adbf07ad4954b8de5dff42c5920831d97b72cf20f83596948cae28a7
这个该怎么使用技术大佬，我看不懂

在2019-08-13 20:54:17，王家启d170302066@st.shou.edu.cn写道：

中文版readme里面已经写得很清楚了，关于release的使用。

以及一些典型用法。

我觉得可以关闭这个问题了，都是readme里面的东西。

**Comment by BingLingGroup** [comment]
@D170302066 拉到下面有assets左边小三角点击展开下载不带pyinstaller的那个即可。
