### ISSUE TITLE
zh_CN cmdline_utils.py translation typo

### ISSUE THREAD

**Issue by pikozizi** [BingLingGroup/autosub#56]
提供的自动翻译ALPHA版本的使用步骤不是看的很明白……是每一步都需要吗？还是只需要做“只是处理过程中的一部分”下面的就可以了呢？
直接运行翻译步骤会出现如下情况：
![image](https://user-images.githubusercontent.com/54091532/62994584-46446900-be8f-11e9-9f20-cedbcf3c0aca.png)

**Comment by pikozizi** [comment]
> 提供的自动翻译ALPHA版本的使用步骤不是看的很明白……是每一步都需要吗？还是只需要做“只是处理过程中的一部分”下面的就可以了呢？
> 直接运行翻译步骤会出现如下情况：
> ![image](https://user-images.githubusercontent.com/54091532/62994584-46446900-be8f-11e9-9f20-cedbcf3c0aca.png)

**Comment by BingLingGroup** [comment]
这个问题已经由该提交[Fix file renaming issues](https://github.com/BingLingGroup/autosub/commit/50da702f9a8ed8fab7d1688c04abb288880b7224#diff-f4f45ccad0cfe327658b8464118e6f93)解决，从dev分支中下载安装最新版即无此问题。
原因是简体中文的翻译文件里把字符串格式化里的关键词变量`dst`不小心改成了`fmt`导致的，纯粹是复制粘贴的时候搞错的，你要是用英文版不会有这个问题。启动英文版的[方法](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#国际化)。
另外就算按照正常处理流程，到这里程序也会退出。如果你要自动匹配语言代码，请使用 `-bm all` 选项。

**Comment by BingLingGroup** [comment]
我觉得可以关闭这个问题了，虽然是个bug但是并不影响正常的运行，而且我已经在dev分支里面修复了，等以后再加到alpha发布版里面。
另外关于具体的使用，参考[典型用法](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#典型用法)中的选项输入即可。
