### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by D170302066** [BingLingGroup/autosub#57]
您好！能对windows版本做一个视频使用教程吗，下载下来的asset不会使用。。如何对视频和音频转为txt，周末就要出差用了。着急看不懂说明文档

**Comment by BingLingGroup** [comment]
我已经写得很清楚了，你只要看[典型用法](https://github.com/BingLingGroup/autosub#typical-usage)就可以了，如果是需要的是翻译的txt，那么使用如下命令即可

`autosub -i 输入文件 -S 语言代码 -D 语言代码 -bm all -F txt`

如果需要的是源语言的txt，使用如下命令即可

`autosub -i 输入文件 -S 语言代码 -bm all -F txt`

如果两者都需要，使用如下命令即可

`autosub -i 输入文件 -S 语言代码 -D 语言代码 -bm all -F txt -of src dst`

如果需要从batch中启动，将以上命令复制粘贴到batch中的相应位置即可

我觉得没必要做视频教程，命令行软件本来也没有什么复杂的交互，输入命令就完了，典型用法我在readme里面给出了，关键的参数都在help里面，而且我全做了汉化，还给了懒人用的批处理，这都看不懂，不想看，没耐心看，也不想用，不会用，又不提出任何细节性的问题，那是你的问题

具体参见[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md#%E5%9C%A8%E6%8F%90%E9%97%AE%E4%B9%8B%E5%89%8D)

>当你提出问题的时候，请先表明你已经做了上述的努力

至于什么时候有空做视频教程推广，那是我有空以后的事情

**Comment by D170302066** [comment]
收到！谢谢您！我学习一下！真对不起大佬！

在2019-08-15 14:58:18，写道：

我已经写得很清楚了，你只要看典型用法就可以了，如果是需要的是翻译的txt，那么使用如下命令即可

autosub -i 输入文件 -S 语言代码 -D 语言代码 -bm all -F txt

如果需要的是源语言的txt，使用如下命令即可

autosub -i 输入文件 -S 语言代码 -bm all -F txt

如果两者都需要，使用如下命令即可

autosub -i 输入文件 -S 语言代码 -bm all -F txt -of src dst

如果需要从batch中启动，将以上命令复制粘贴到batch中的相应位置即可

我觉得没必要做视频教程，命令行软件本来也没有什么复杂的交互，输入命令就完了，典型用法我在readme里面给出了，关键的参数都在help里面，而且我全做了汉化，还给了懒人用的批处理，这都看不懂，不想看，没耐心看，也不想用，不会用，又不提出任何细节性的问题，那是你的问题

具体参见提问的智慧

当你提出问题的时候，请先表明你已经做了上述的努力

至于什么时候有空做视频教程推广，那是我有空以后的事情

**Comment by BingLingGroup** [comment]
你回信刚才暴露实名了，下次注意一下邮件落款。

**Comment by D170302066** [comment]
我桌面有个mp3文件，路径是F:\桌面\new180518.mp3，我想导出字幕，但是不成功，您看下我error行错在哪里，感谢！
F:\桌面\autosub\autosub>autosub -i/F:\桌面\new180518.mp3 en-US
usage:
用法：autosub [-i 路径] [选项]
autosub: error: unrecognized arguments: en-US

F:\桌面\autosub\autosub>autosub [-i/F:\桌面\new180518.mp3][en-US]
usage:
用法：autosub [-i 路径] [选项]
autosub: error: unrecognized arguments: [-i/F:\桌面\new180518.mp3][en-US]

F:\桌面\autosub\autosub>

在2019-08-15 14:58:18，王家启d170302066@st.shou.edu.cn写道：

我已经写得很清楚了，你只要看典型用法就可以了，如果是需要的是翻译的txt，那么使用如下命令即可

autosub -i 输入文件 -S 语言代码 -D 语言代码 -bm all -F txt

如果需要的是源语言的txt，使用如下命令即可

autosub -i 输入文件 -S 语言代码 -bm all -F txt

如果两者都需要，使用如下命令即可

autosub -i 输入文件 -S 语言代码 -bm all -F txt -of src dst

如果需要从batch中启动，将以上命令复制粘贴到batch中的相应位置即可

我觉得没必要做视频教程，命令行软件本来也没有什么复杂的交互，输入命令就完了，典型用法我在readme里面给出了，关键的参数都在help里面，而且我全做了汉化，还给了懒人用的批处理，这都看不懂，不想看，没耐心看，也不想用，不会用，又不提出任何细节性的问题，那是你的问题

具体参见提问的智慧

当你提出问题的时候，请先表明你已经做了上述的努力

至于什么时候有空做视频教程推广，那是我有空以后的事情

**Comment by D170302066** [comment]
谢谢您！我输入了 autosub -i F:\桌面\new180518.MP3 -S en-US -bm all -F txt 后，出现了2个问题：1.翻译目的语言未提供。只进行语音识别。en-US应该是谷歌支持的语言吧。或者支持语言列表应该在哪里查。2.将短片段语音发送给API并得到识别结果。
语音转文字中： N/A% |                                                                                      | ETA:  --:--:-- 一直停留在这里不动，是否有办法解决。

在2019-08-15 15:46:58，写道：

你回信刚才暴露实名了，下次注意一下邮件落款。

**Comment by BingLingGroup** [comment]
1. 连接谷歌服务器需要代理，我想这个不需要我重复说了吧。代理的设置[参见](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E9%80%89%E9%A1%B9)。你再加一个`-hsp`，代表使用`https://127.0.0.1:1080`作为https代理。需要自定义代理地址和端口的话可以输入`-hsp`后在后面添加参数如`https://x.x.x.x:xxxx`。shadowsocks-windows的本地https代理默认端口是1080，直接用`-hsp`即可。至于其他代理软件请自己确认。
2. 查看支持的语言选项在[这里](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E9%80%89%E9%A1%B9)有，我不重复了。
3. 请不要照抄，请提供目的语言选项 `-D`。另外语音识别语言代码和目的语言代码不一样，[参见](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#语音转文字翻译语言支持)。

**Comment by ismuta** [comment]
It's all about Chinese. I cannot unterstand anything.

Video tutorial would be very useful to us.

The other repo video tutorial: https://www.youtube.com/watch?v=IAuUgL5cVXY

**Comment by BingLingGroup** [comment]
@ismuta  **Readme is English by default. Why can't you read it?**
If you have anything to ask after reading the readme, you can raise an issue.

**Comment by webberian** [comment]
> Video tutorial would be very useful to us.

If you want a graphical interface for autosub, have a look at this project: https://github.com/raryelcostasouza/pyTranscriber

**Comment by BingLingGroup** [comment]
@davdavf Honestly speaking, pyTranscriber has less features than the autosub. And perhaps autosub will get a GUI in the future.
There's a video tutorial somewhere on the Internet. So I'm closing this issue now.
