### ISSUE TITLE
http proxy issues

### ISSUE THREAD

**Issue by D170302066** [BingLingGroup/autosub#58]
执行mp3转文字，到这一步，不再往下运行。是否有win10下稳定google api接入方法。
```
将短片段语音发送给API并得到识别结果。
语音转文字中： N/A% |                                                                                         | ETA:  --:--:--
```

已经连接ssr，新加坡代理，识别的是en。英文语音。

**Comment by BingLingGroup** [comment]
先给出你的参数，你有没有输入`-hsp`选项。至于http代理[设置](https://github.com/BingLingGroup/autosub/issues/57#issuecomment-521841359)问题，我这里已经说了，不再重复。
建议安装`curl`来检测当前终端的IP。
如果你是windows，且没有安装chocolatey包管理器，请先输入以下命令中的第一行来安装chocolatey。

```bash
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
choco install curl
set http_proxy=http://127.0.0.1:1080
curl ipinfo.io
```

查询出来的IP如果是你的代理IP，说明`http://127.0.0.1:1080`的代理成功，接下来再运行autosub。

如果代理成功，但依然无法使用autosub，说明你的代理可能不够稳定，请使用readme中的telegramchannel推荐的代理。

**Comment by BingLingGroup** [comment]
另外win10下应该是可用的，除非提供更多log，否则说明就是你的网络问题。

**Comment by D170302066** [comment]
我在转文件中，得到以下错误：将短片段语音发送给API并得到识别结果。
语音转文字中： N/A% |                                                                                         | ETA:  --:--:--^CTraceback (most recent call last):
 File "F:\桌面\autosub\autosub\__main__.py", line 29, in <module __parents_main__>
 File "F:\桌面\autosub\autosub\multiprocessing\spawn.py", line 74, in freeze_support
 File "F:\桌面\autosub\autosub\multiprocessing\spawn.py", line 100, in spawn_main
 File "F:\桌面\autosub\autosub\multiprocessing\reduction.py", line 86, in steal_handle
PermissionError: [WinError 5] 拒绝访问。


在2019-08-17 09:08:04，@st.shou.edu.cn写道：

另外win10下是绝对可用的，你用不了完全是你的网络问题。

**Comment by D170302066** [comment]
翻墙用的是SSR，服务器位于新加坡。已经按照curl一套操作下来。但是还是无法调用API。
F:\桌面\autosub\autosub>curl ipinfo.io
{
 "ip": "*.*.*.*",
 "city": "Beijing",
 "region": "Beijing",
 "country": "CN",
 "loc": "*.*",
 "org": "AS4808 China Unicom Beijing Province Network",
 "readme": "https://ipinfo.io/missingauth"
}
F:\桌面\autosub\autosub>

在2019-08-17 09:08:04，@st.shou.edu.cn写道：

另外win10下是绝对可用的，你用不了完全是你的网络问题。

**Comment by BingLingGroup** [comment]
@D170302066 这IP显然不是你的代理IP啊，这是一个国内的IP怎么可能连得上谷歌。
我说了，要么加`-hsp`，要么在运行autosub前先输入这行命令`set https_proxy=https://127.0.0.1:1080`设置代理。当然首先确认你本地代理的http端口是多少。譬如shadowsocks-windows默认本地http代理端口是1080。这些你都不说我怎么知道你问题出在哪里。
