### ISSUE TITLE
Better support for unstable network?

### ISSUE THREAD

**Issue by linwe2012** [BingLingGroup/autosub#60]
我在使用的时候会发现程序进度条常常会卡住。可能是我的梯子不够稳定，请问能不能给不大稳定的网络提供支持？比如超时重新请求等等？

**Comment by BingLingGroup** [comment]
已经自带超时重新请求三次，至于梯子不稳定自己解决，可以使用服务器远程操作，或者使用readme里的telegram频道里推荐的稳定梯子。（不保证效果，需要自己购买测试，所以未明确在readme中提及）
api只支持http/https协议，没查到有什么额外的参数，理论上没办法断点续传。
