### ISSUE TITLE
有两个小问题

### ISSUE THREAD

**Issue by hpp0hpp** [BingLingGroup/autosub#61]
环境是Windows。
1. 创建的字幕如果有同名文件的话，会提示重新输入输出路径，但我重新输入的文件路径的后缀名会被省略掉了。创建出一个没有后缀名的文件。
2. /- D 的language code如果输入的不在list中，比如我输入了en-US，会有KeyError“fmt”的错误提示，但改成-D en就没有了。 这个我研究了好久才发现，是否这里也可以有一个容错机制？

**Comment by BingLingGroup** [comment]
1. 没错，这是个bug，不过我已经在[提交 50da702](https://github.com/BingLingGroup/autosub/commit/50da702f9a8ed8fab7d1688c04abb288880b7224)里修复了。
2. 这也是个bug，也在[提交 50da702](https://github.com/BingLingGroup/autosub/commit/50da702f9a8ed8fab7d1688c04abb288880b7224)里修复了。

以上两个修复没有在最新的0.5.1a发布中包含，没想到都被你试出来了……你可以使用readme里介绍的pip安装的方法来安装最新版。0.5.2a短时间内不会发布。

**Comment by BingLingGroup** [comment]
新的版本发布之后我再关闭这个问题，现在先留着。

**Comment by BingLingGroup** [comment]
新版本已发布~
