### ISSUE TITLE
有个关于翻译的bug

### ISSUE THREAD

**Issue by hpp0hpp** [BingLingGroup/autosub#62]
[testTrans.zip](https://github.com/BingLingGroup/autosub/files/3568320/testTrans.zip)
仍然在windows下测试。
附件的两个字幕文件仅有少量差异，但一个就会翻译失败，一个会翻译成功。
不太清楚哪里出了问题。

**Comment by BingLingGroup** [comment]
收到，马上测试

**Comment by BingLingGroup** [comment]
我知道问题了，主要是最后一行是空行，翻译方法在翻译的时候会忽略掉最后的空行，所以导致翻译出来的文本行数和翻译前的文本行数不一致，我这里采取很严格的判断，如果行数不一致会直接报错放弃翻译，所以就出错了。

这个是我程序的问题，因为Py-googletrans是按行发出请求，感觉有点太多了怕被封，于是我就给Py-googletrans做点优化，减少请求次数，按照4000半角字符/1000全角字符的长度来做的（之所以不是二分之一，大概是Py-googletrans的接口的bug，参见 #49 ），所以这里面就复杂了，需要判断有效行的始末位置，需要记录每次请求的行的位置，改了好几次，结果没想到最后空行的问题没有解决，其实结尾留有空行是比较常见的情况。

原因是因为最后一组记录始末位置的列表，末位置比原行数少，漏掉了那些空行，但是循环判断条件是始末位置列表用完了就退出，所以后面那些空行就没有被记录到翻译结果里，出来以后判断长度不一致就退出了。

**Comment by BingLingGroup** [comment]
[提交 0e1192c](https://github.com/BingLingGroup/autosub/commit/0e1192c5bbbb6e85527f6d5fad35abbe62f0f709)应该能修复这个问题，你可以试着安装一下最新版。非常感谢你的问题。

**Comment by hpp0hpp** [comment]
@BingLingGroup   嗯嗯，非常感谢您，我主要是想看一个discovery的系列纪录片，但很多专业名词听不明白，所以发现了楼主的工具非常好用，非常感谢。不过我是个财务，编程能力非常基础，只能发现问题了，解决能力非常有限。
另外能不能遇到即使是翻译错误，也能输出原始语言的字幕文件。这样我们就可以下次仅调用翻译API或者使用其他翻译工具进行字幕翻译，而不是重新分离语音文件，重新语音识别了。再次感谢楼主。

**Comment by BingLingGroup** [comment]
现在是有这个功能的，你只需要使用`-of all`或者`-of src`即可，参见[典型用法-输出语音语言字幕](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#语音转录为字幕)。关于该选项的详细说明可以在[readme](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#选项)也就是帮助信息里面找到。

**Comment by hpp0hpp** [comment]
好的，可能是我一直选的是双语，所以失败了，就没有生成字幕。
