### ISSUE TITLE
转换文件的效率问题 以及 flac源文件输入仍然被转换的问题

### ISSUE THREAD

**Issue by hpp0hpp** [BingLingGroup/autosub#63]
正在windows环境下使用您的工具进行批量语音识别，发现：
1.长度较长的视频文件转换成Flac的效率特别低，相较于格式工厂来讲，应该用了十倍以上的转换时长，同时占用了大量CPU。这个可能是ffmpeg的问题，但不知道格式工厂是通过什么技术搞定的。
2. 使用格式工厂转换成flac后，再进行语音识别效率明显提高，但发现有重复动作，源文件是flac，仍然进行了flac的转换。

为API转换为"C:\Users\admin\AppData\Local\Temp\tmp959mywna.flac"。
ffmpeg.exe -hide_banner -y -i "C:\Users\admin\Downloads\Compressed\autosub\S06E09.flac" -ac 1 -ar 44100 "C:\Users\admin\AppData\Local\Temp\tmp959mywna.flac"

**Comment by hpp0hpp** [comment]
![image](https://user-images.githubusercontent.com/54829297/64422867-a8336f80-d0d7-11e9-8b5f-21144b58e308.png)
从进程上来看，格式工厂也是利用了ffmpeg，但不知道为什么效率差那么多。

**Comment by BingLingGroup** [comment]
这个大概是因为转换参数的原因，你可以适当把采样率调低，我这个采样率是按照最高的水准进行的。采样率可以调整，但我不保证调整以后的采样率会被api接受，需要你自己测试。以及禁止音频再处理的选项，我都有提供，readme里面的音频处理选项里对这些选项都有说明，我这里不再赘述。

**Comment by BingLingGroup** [comment]
这确实是个bug，是我的ffmpeg参数有点问题，详见 #66，现在已经修复，尚未发布
