### ISSUE TITLE
在googleCloud上用的问题

### ISSUE THREAD

**Issue by zhuangwen1979** [BingLingGroup/autosub#64]
装的是ubuntu，运行命令后，到下面就停了

ffprobe /tmp/tmpV5Ir9V.wav -show_format -pretty -loglevel quiet
Killed

然后就跳到root@iXXXXXX-1:了，请问这是怎么回事 ，没有转换成FLAC也没有传出去

**Comment by BingLingGroup** [comment]
你试试单独使用 ffprobe 看看，另外下次请按照格式提 issue

**Comment by zhuangwen1979** [comment]
嗯，好的。好像是内存不够的问题。谢谢

**Comment by BingLingGroup** [comment]
你是多小的内存啊……我之前试过 256MB 大概有 128MB 空闲的都可以，另外你可以在本地预处理成指定的格式，[这里](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#输入)有说明，然后使用 `-ap n` 选项可以避免音频再编码，但是音频分割（非编码）是一定需要的

**Comment by zhuangwen1979** [comment]
主要自己不懂编程，本地windows下是没问题啊，但问题翻墙上传那速度太感人了，不懂为何要用flac格式，3M的MP3也能整到快200M。在换了N个版本系统和硬件后，乱折腾好一阵，通过网上相关文章总算还是在谷歌虚拟机ubuntu系统下配置好了，但有个新的问题。用自带免费的翻译引擎能正常出字 ，但我在google上申请了Cloud Speech-to-Text API了，也开启了。也创建了API密钥，命令也是autosub -S zh  -bm all -gsv2 XXX  -i test.mp3为何出来的没有任何字,用自带的就没问题。
自带翻译的中文水平不大行，不如网易的见外

**Comment by BingLingGroup** [comment]
这个不是Cloud Speech API #10 
另外自带的免费翻译用的是py-googletrans，我[简介](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#介绍)里面说了，就是谷歌翻译的网页版，请不要拿付费服务标准要求免费服务
Cloud Speech API和网易见外这些以后会考虑加入，另外我个人不推荐直接将语音识别的结果进行翻译的，就算网易见外再好，你还是要进行校对的，这方面我建议使用subtitleedit配合其自带的谷歌翻译进行字幕制作

**Comment by BingLingGroup** [comment]
至于为什么需要flac，他那个api的[文档](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E8%BE%93%E5%85%A5)说只支持flac，至于别的格式是否支持，你可以自己修改后进行尝试，还是一样的，你想要保持输入的格式不变，可以使用 `-ap n` 选项，这样输入以后程序不会对你的输入格式进行修改，只会使用ffmpeg对音频进行非编码分割，分割时也不会改变格式
