### ISSUE TITLE
mac crash

### ISSUE THREAD

**Issue by jim1019** [BingLingGroup/autosub#65]
环境 mac py2.7

命令：autosub "123.mp4" -S zh-CN -D zh-CN

错误：
objc[39667]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[39668]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[39668]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[39669]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[39669]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug. 

求问一下这个会是什么问题，如何解决？

**Comment by BingLingGroup** [comment]
请严格按照模板填写问题，很多模板上要求的信息你没有填写

**Comment by jim1019** [comment]
> 请严格按照模板填写问题，很多模板上要求的信息你没有填写

抱歉信息填少了。我发现从origin分支安装是运行不了的，从alpha分支安装是可以运行

**Comment by BingLingGroup** [comment]
这我就不太清楚了，也许跟这个问题有关 #47 ，因为origin分支实在太过久远，有些问题不再修复
[参考](https://github.com/jitingcn/autosub/commit/1cb0a6461ef1f451699d40da07cf0dcf9e742054#diff-47566c2cb6ebd6055fb1ba9a15f0b7b2R71)

> 好吧，这个地方确实是有点用的，不过对应的是unix shell=True可以开启string输入命令行指令，而False则是用list，而在windows平台上则两者皆可……而为了防止shell注入漏洞，python官方是不建议用shell=True的，所以需要用另外一个split工具，不过那个split工具又不能在windows平台的指令上用，所以还是得对平台做判断。
> 参考资料：https://stackoverflow.com/questions/33560364/python-windows-parsing-command-lines-with-shlex

origin分支中可能出问题的[代码部分](https://github.com/BingLingGroup/autosub/blob/origin/autosub/__init__.py#L73)
