### ISSUE TITLE
High memory/RAM usage

### ISSUE THREAD

**Issue by snippins** [BingLingGroup/autosub#67]
**Describe the bug**
Compare to the original autosub, it seems to use a lot of memory. It uses over 4.5 Gb for a 5 hours audiobook (measured using [ps_mem](https://github.com/pixelb/ps_mem) on Ubuntu). Is it possible reduce somehow? Thank you.

**Comment by BingLingGroup** [comment]
Have you tried this solution #66 or the latest dev version? I guess it will help.

**Comment by snippins** [comment]
I just tried the latest dev. It gets a bit better memory wise. 3.7G for a 5 hours audiobook now. It also seems to run faster.

Edit: It has just gone up to 4.3 Gb in the Speech-to-Text step, still a little bit better than 4.5G though.

**Comment by BingLingGroup** [comment]
I've tried `.aac` format which obviously can reduce memory usage when transcoding. It seems the api don't accept it. So this issue may be solved under other apis.

**Comment by BingLingGroup** [comment]
OK, it seems I can fix this partially in 3 ways.

1. Terminate childprocess and join them after multiprocessing done.
2. Use `gc.collect(0)` to reduce memory usage and collect garbage after Auditok detection and multiprocessing calls.
3. Modify default multiprocessing concurrency to core count but not less than 2.

As well as further optimization, currently I could think about is #81 .

**Comment by BingLingGroup** [comment]
Commit https://github.com/BingLingGroup/autosub/commit/f41c8468cc352e44379903cfcf0e81fbcf4833d9 should partially fix this. Thanks for your issue.
