### ISSUE TITLE
麻烦问一下，什么时候会更新alpha分支？现在还停留在0.5.1a上，希望能尽快享受新功能和优化，谢谢

### ISSUE THREAD

**Issue by libukai** [BingLingGroup/autosub#71]
**Make sure you have read the readme, searched and read the issues related to yours. Otherwise it will be considered as a duplicate which will be closed immediately.**

**Is your feature request related to a problem? Please describe.** (Optional)

**Describe the solution you'd like**

**Describe alternatives you've considered** (Optional)

**Additional context** (Optional)

**Comment by BingLingGroup** [comment]
刚才更新了，之前是我忘了，对Git操作还不太熟。
关于dev分支的新提交，我想再修改一些功能之后再发布新版本并添加到alpha里，你急的话直接从dev分支安装就好了。
