### ISSUE TITLE
-o / --output 参数被input参数覆盖

### ISSUE THREAD

**Issue by czastack** [BingLingGroup/autosub#73]
**描述问题**
-o 指定输出文件无效，关联代码
https://github.com/BingLingGroup/autosub/blob/alpha/autosub/cmdline_utils.py#L206-L218

**复现问题**
复现问题的步骤:
1. 命令
```
autosub -i audio.flac -o 1.srt
```
2. 输出
```
Error: Output subtitles format "flac" not supported. Run with "-lf"/"--list-formats" to see all supported formats.
Or use ffmpeg or SubtitleEdit to convert the formats.
```

**操作环境：**
 - 操作系统: Ubuntu 16.04
 - Python版本: Python 3.7.4
 - Autosub版本: autosub-0.5.2a0

**Comment by BingLingGroup** [comment]
提交 https://github.com/BingLingGroup/autosub/commit/3a940924356664919e0f2cdb6c24fed040cfc88c 应该能修复这个问题，你可以试着安装一下dev分支上的最新版。非常感谢你的问题。
