### ISSUE TITLE
音频转换为多个短语音片段 这个功能太耗费CPU

### ISSUE THREAD

**Issue by oonice** [BingLingGroup/autosub#74]
**描述问题**
2小时的英文视频文件通过下面的命令达到识别语音提取出英文字幕
autosub -i ss1.mp4 -S en
问题就出在 “按照语音区域将音频转换为多个短语音片段”，实在是太慢了，我英特尔CPU在这个进度条百分比卡的电脑完全不能有其他操作，搞了5分钟才20%实在受不了就手动暂停了。

**期待的行为**
能不能把这个“多个短语音片段”同时处理的数量变少一点，或者使用核显硬解来处理，还有单线程来处理最好了，这样就能不影响电脑其它操作了。

**操作环境（请提供以下完整数据）：**
 - 操作系统: [ windows 7]
 - Python版本: [ Python 3.7]
 - Autosub版本: [0.5.3-alpha]

**Comment by BingLingGroup** [comment]
0.5.3-alpha已经是修复过转码耗时较长问题的版本了，现在已经是只处理音频了。我使用的7700HQ在修复之前就能较为流畅地运行，不知道你的CPU什么型号。
至于能否开硬解加速转码，这个我不太清楚ffmpeg是否支持，可以研究下。
另外首先需要研究下免费api是否接受有损格式，这样可以节约存储和网络IO，这里也有可能是存储IO瓶颈。

**Comment by oonice** [comment]
我的是比较老的低压笔记本了，我也使用ffmpeg处理过一些事情，一般通过h264_qsv硬解处理视频是压力不大的，以前音频不知道硬解代码直接软处理完全没有什么多少CPU占用速度也很快。
我看这个程序是在本地生成了非常多那种好像是无损音频格式的文件，不知道是因为一下子生成的数量太多导致的卡，还是因为这个格式的处理问题，反正以前单线程软解处理音频的格式有mp3 m4a aac都没有出现过这种事情。

**Comment by BingLingGroup** [comment]
@heiyutian https://github.com/BingLingGroup/autosub/blob/dev/autosub/constants.py#L87-L91 所有的音频转换命令（ffmpeg）都在这里，如果你有更好的参数，可以跟我说，或者自己pull request

**Comment by BingLingGroup** [comment]
> 0.5.3-alpha已经是修复过转码耗时较长问题的版本了，现在已经是只处理音频了。我使用的7700HQ在修复之前就能较为流畅地运行，不知道你的CPU什么型号。
> 至于能否开硬解加速转码，这个我不太清楚ffmpeg是否支持，可以研究下。
> 另外首先需要研究下免费api是否接受有损格式，这样可以节约存储和网络IO，这里也有可能是存储IO瓶颈。

已测试，免费api无法接受`.aac`格式，建议降低`.flac`采样率来减少消耗。

**Comment by jitingcn** [comment]
这里应该是IO瓶颈，在trim短片段之前已经完成了转码，copy基本上是纯IO操作了

**Comment by BingLingGroup** [comment]
@heiyutian 另外`把这个“多个短语音片段”同时处理的数量变少一点`现在已经有这个功能了，调整`-ac`选项即可，默认值为10并行数量，你可以适当调低。

**Comment by oonice** [comment]
具体一键命令是什么 我尝试
autosub -i ss1.mp4 -S en -ac 1, --audio-concurrency 1
提示 autosub: error: argument -ac/--audio-concurrency: invalid int value: '1,'
我想一条命令把视频给识别语音出字幕且翻译有没有办法

**Comment by BingLingGroup** [comment]
@heiyutian 大兄弟你是不是不会输命令行参数。
`-ac 1`或者`--audio-concurrency 1`而不是两个一起输入。
readme里面已经给出了同时翻译的用法。 https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#翻译字幕

**Comment by oonice** [comment]
我记录了40分钟的过程，从下面的3小时的TS格式视频开始
使用命令 autosub -i ss1.ts -S en -ac 1
程序先提取出wav音频文件  这个步骤没有什么CPU和硬盘及IO的占用。速度很快（一分钟左右）。
之后会转换成无损音乐的flac格式  这个步骤没什么CPU占用，IO占用小高和硬盘占用很高。速度快（一分钟左右）。
第三步就是分解成非常多的flac小文件，这个步骤因为前面设置了1所以速度很慢，CPU占用了30%，IO每隔20多秒有3秒的超高占用，硬盘没什么占用。速度（40分钟分解进度50%）


我个人在前几天还没有知道这个程序的时候，是通过命令ffmpeg快速（一分钟左右）copy出音频m4a文件（100M左右），然后通过ffmpeg把这个m4a与一张图片合成视频，由于我设置成1秒一帧所以视频文件很小（200M多点），并且合成速度非常快（几分钟内）。这里的两个命令只有第二项CPU占用有30%之外，没什么IO和硬盘的占用。然后上传到油管之后，油管会自动生成机器人字幕，然后通过别的油管字幕下载网站去下载翻译后的字幕。

小结
我知道这个程序需要分解成非常多的小文件去应对谷歌的API限制，但是这个步骤不知道是不是能找到一个更简单快速的方法呢。

**Comment by BingLingGroup** [comment]
@heiyutian IO是指网络IO的占用吗？使用FLAC会占用网络带宽是很显然的事情，但是正如readme里面所说，只支持FLAC和PCM，我印象里FLAC会比同采样率/同位率的PCM更省空间，且api能接受的FLAC的位率更高，所以就没考虑PCM格式（可以考虑增加支持）。

我觉得分割FLAC应该不会占用到CPU才对，当然我也没观察过CPU占用，不好下结论。
如果你想用的片源可以使用油管，当然用油管最好，免费API肯定比不上油管。
另外我刚才在研究cloud speech api，即使是付费的cloud speech api，其能接受的格式也只有

https://cloud.google.com/speech-to-text/docs/encoding?hl=zh-cn

编解码器 | 名称 | 无损 | 使用说明
-- | -- | -- | --
MP3 | MPEG 第三层音频 | 否 | 仅提供 Beta 版。如需了解详情，请参阅 RecognitionConfig 参考文档。
FLAC | 免费无损音频编解码器 | 是 | 信息流要求使用 16 位或 24 位的位深
LINEAR16 | 线性 PCM | 是 | 16 位线性脉冲编码调制 (PCM) 编码
MULAW | μ 律 | 否 | 8 位 PCM 编码
AMR | 自适应多速率窄带 | 否 | 采样率必须为 8000 Hz
AMR_WB | 自适应多速率宽带 | 否 | 采样率必须为 16000 Hz
OGG_OPUS | Ogg 容器中的 Opus 编码音频帧 | 否 | 采样率必须为 8000 Hz、12000 Hz、16000 Hz、24000 Hz 或 48000 Hz 之一
SPEEX_WITH_HEADER_BYTE | Speex 宽带 | 否 | 采样率必须为 16000 Hz

所以m4a（其实是`.aac`编码）就不要想了，无论免费或者付费的google speech api都是不可能的。

google speech api有长音频识别和短音频识别的区分，长音频识别加上[获取字词时间戳](https://cloud.google.com/speech-to-text/docs/async-time-offsets?hl=zh-cn)的功能（时间戳精度达到每个单词），就基本和youtube差不多了。

不过youtube不能识别中文，所以究竟是适合用youtube还是api就见仁见智了。

**Comment by jitingcn** [comment]
之前我有想过那种思路，先使用长音频识别然后用字词时间戳来分隔出每句话，测试后发现那个字词时间戳基本是不准确的，对于字幕需要的精确度来说基本没法用。可能可行的方法只有先确定语音区域在给API识别。
不过我测试的是日语文本，可能英语的效果会好一些。(或者说只有英语能用)

PCM基本不用考虑,未压缩的波形文件的大小肯定是更大的,至于FLAC是可以选择压缩比的,最大压缩的情况下会比原始PCM节约很多存储空间

实际上YouTube自动字幕的效果还是相当不错的...

**Comment by oonice** [comment]
BingLingGroup  我用的Process Explorer管理器在监控各项数据，IO就是那个软件里面的IO，用油管的话那边有些时候还是会碰到版权问题的，至于我说的m4a格式只是因为这个视频本身通过copy命令快速提取很有用，我试了m4a和aac可以很快，mp3是不行的需要转格式一次，这些其实都不是问题，通过ffmpeg转一下格式成比如MP3也是超级快的，这个autosub程序本身不就是先有一次从wav转到flacd的过程，然后才分解的flac吗。

jitingcn 油管字幕有两个问题，一个是音乐版权问题，还有就是我的操作步骤可能不适合其他人，还是有点繁琐的，我自己也想着省事，所以就找到了autosub这个程序，想试着看看能不能一个命令搞定一切。

**Comment by BingLingGroup** [comment]
@jitingcn 原来FLAC还可以调整压缩比……我有空研究下。
youtube自动字幕的问题主要是识别语言比较有限，总之中文就不支持。当然这个api的中文识别率也不是很理想。

**Comment by BingLingGroup** [comment]
@heiyutian 并非如此，我后来进行了修改，去除了从WAV转FLAC的过程，因为有损耗。但是因为需要给auditok用，以及获得音频长度，需要把源文件转成WAV使用，但是不影响后面的FLAC，后面的FLAC是从源文件重新转的。

**Comment by oonice** [comment]
刚刚试了一下直接从视频copy出wav和m4a文件，发现wav的时间长度是不对的，多了半个多小时，如果再从m4a用copy可以秒转wav时间长度不会变。

**Comment by jitingcn** [comment]
> 刚刚试了一下直接从视频copy出wav和m4a文件，发现wav的时间长度是不对的，多了半个多小时，如果再从m4a用copy可以秒转wav时间长度不会变。

如果编码格式不同是不能使用copy的，没有意义。假设m4a容器里的是正确的aac编码，使用copy转换wav还是aac编码，并没有实际转码过程，是错误的操作
同时理论上也不能视频直接copy出wav，除非视频的音频流本身就是wav格式

**Comment by oonice** [comment]
我这里提wav是想说软件如果是用wav来获取时间长度，可能会不准确导致其它的问题，因为去之前那40分钟的记录里面就是wav

**Comment by BingLingGroup** [comment]
@heiyutian 我记得是因为auditok只能接受wav，所以用了wav格式来获取时间轴，时间轴是由auditok生成的。
另外获取时间长度是以前不用auditok的版本里有，后来改用auditok了以后就没用了，我应该改一下那个消息。

**Comment by last2win** [comment]
默认的10个并发太耗内存了，我刚试了一下，40M的音频，瞬间就爆了2G的内存。
默认并发可以调小一些。

**Comment by BingLingGroup** [comment]
@zhang0peter 好的，默认并发我调为cpu核心数吧。
看了下，`multiprocessing.cpu_count()`好像包括了超线程，那我暴力除以2吧……

**Comment by last2win** [comment]
> @zhang0peter 好的，默认并发我调为cpu核心数吧。
> 看了下，`multiprocessing.cpu_count()`好像包括了超线程，那我暴力除以2吧……

早上我试了一下，`Converting speech regions to short-term fragments.`这个阶段耗CPU，但影响不大；`Sending short-term fragments to Google Speech V2 API and getting result.`这个阶段很占内存，40M的音频，最多的时候用了2.5G内存，我在服务器上开了3G虚拟内存才撑过去。

**Comment by BingLingGroup** [comment]
@zhang0peter 给Google V2 API发数据耗内存，我能想到的只有把音频数据读入内存以后没被释放掉，我会考虑把释放内存的语句加进来。
关于Auditok识别语音区域的部分，它给我语音区域之前我没法控制它内部的内存分配，而且最后会返回一个包含音频数据的列表，这个东西累积起来就会变得特别大，我只能处理以后才能把它销毁掉。当然，我估计还有别的流式的方法应该可以做到边处理边销毁，我等会研究下。
另外新版本已经支持Google Cloud Speech-to-Text API了，那个支持OGG_OPUS有损格式，你可以考虑用那个来节省内存&外存&带宽。这个API每个月有60分钟免费额度，当然如果你拿了那个300刀白嫖体验金更佳，那个是Google Cloud Platform产品通用的，这个API也可以用。
关于OGG_OPUS使用的方法：
`autosub -i 输入文件 -sapi gcsv1 -asf .ogg -asr 48000 ...(其他选项)`

---

Auditok好像没有文件输入的流式的方法……另外我把多进程的数量设置为核心数（包括超线程的数目）除以2并最小为2，进程池在使用完之后全部`terminate()`并`join()`（这个应该能节省大量内存……之前一直没写这个，以为是自动的），多进程执行的那几个函数都加了调用完之后立刻用`gc.collect(0)`回收垃圾，这样应该能大幅减少内存以及CPU消耗。
