### ISSUE TITLE
更新windows后无法使用：WinError 193

### ISSUE THREAD

**Issue by jsuispersonne** [BingLingGroup/autosub#75]
如题，使用anaconda运行32位python后依然在音频返回本地时出现同样的问题：
OSError: [WinError 193] %1 不是有效的 Win32 应用程序
操作环境：
 - 操作系统:windows10
 - Python版本: Python 2.7
如图
![微信图片_20200127014942](https://user-images.githubusercontent.com/59540895/73144560-5354bd80-40a7-11ea-9382-c221543b5b63.jpg)

**Comment by BingLingGroup** [comment]
32位python我平时不怎么用，无法排查，你可以试试64位python。
另外请严格按照格式提issue。
