### ISSUE TITLE
macOS command not found: autosub

### ISSUE THREAD

**Issue by findcoins** [BingLingGroup/autosub#85]
**描述问题**
git clone 仓库之后在setup.py所在目录执行pip install .
然后cd到~下执行 autosub -h 提示zsh: command not found: autosub
同时，updatedb之后使用locate autosub 找不到仓库目录之外的其他autosub文件

注：我使用原作者pip install autosub是可以使用的。 但是他好像不支持mono之外的音频，我试了各种办法，用原作者的那个版本都导出0kb的字幕文件

系统macOS 10.14.5
python: 2.7.10

安装信息：
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Defaulting to user installation because normal site-packages is not writeable
> Processing /Users/findcoins/work/private/OpenSource/autosub
> Requirement already satisfied: requests>=2.3.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (2.22.0)
> Requirement already satisfied: pysubs2>=0.2.4 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (0.2.4)
> Requirement already satisfied: progressbar2>=3.34.3 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (3.47.0)
> Requirement already satisfied: auditok>=0.1.5 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (0.1.5)
> Requirement already satisfied: googletrans>=2.4.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (2.4.0)
> Requirement already satisfied: langcodes-py2>=1.2.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (1.2.0)
> Requirement already satisfied: wcwidth>=0.1.7 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from autosub==0.5.4a0) (0.1.8)
> Requirement already satisfied: google-cloud-speech>=1.3.1 in /Library/Python/2.7/site-packages (from autosub==0.5.4a0) (1.3.2)
> Requirement already satisfied: certifi>=2017.4.17 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->autosub==0.5.4a0) (2019.11.28)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->autosub==0.5.4a0) (3.0.4)
> Requirement already satisfied: idna<2.9,>=2.5 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->autosub==0.5.4a0) (2.8)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from requests>=2.3.0->autosub==0.5.4a0) (1.25.8)
> Requirement already satisfied: six in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from progressbar2>=3.34.3->autosub==0.5.4a0) (1.14.0)
> Requirement already satisfied: python-utils>=2.3.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from progressbar2>=3.34.3->autosub==0.5.4a0) (2.3.0)
> Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.14.0 in /Library/Python/2.7/site-packages (from google-cloud-speech>=1.3.1->autosub==0.5.4a0) (1.16.0)
> Requirement already satisfied: setuptools>=34.0.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (44.0.0)
> Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (2013.7)
> Requirement already satisfied: futures>=3.2.0; python_version < "3.2" in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (3.3.0)
> Requirement already satisfied: google-auth<2.0dev,>=0.4.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (1.11.2)
> Requirement already satisfied: protobuf>=3.4.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (3.11.3)
> Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /Library/Python/2.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (1.51.0)
> Requirement already satisfied: grpcio<2.0dev,>=1.8.2; extra == "grpc" in /Library/Python/2.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (1.27.2)
> Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Python/2.7/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (0.2.8)
> Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (3.1.1)
> Requirement already satisfied: rsa<4.1,>=3.1.4 in /Users/findcoins/Library/Python/2.7/lib/python/site-packages (from google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (4.0)
> Requirement already satisfied: enum34>=1.0.4; python_version < "3.4" in /Library/Python/2.7/site-packages (from grpcio<2.0dev,>=1.8.2; extra == "grpc"->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (1.1.6)
> Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Library/Python/2.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=0.4.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-speech>=1.3.1->autosub==0.5.4a0) (0.4.8)
> Installing collected packages: autosub
>   Attempting uninstall: autosub
>     Found existing installation: autosub 0.5.4a0
>     Uninstalling autosub-0.5.4a0:
>       Successfully uninstalled autosub-0.5.4a0
>     Running setup.py install for autosub ... done
> Successfully installed autosub-0.5.4a0

**Comment by BingLingGroup** [comment]
我没有macOS环境，建议阅读 https://github.com/agermanidis/autosub/issues/144#issuecomment-534810438
至于多声道音频，原版应该也会将其自动转换为单声道音频，不存在不支持的问题，不支持只是说API是不支持多声道的音频，但是autosub会帮你把输入转换成符合API要求的再上传，所以这个问题不需要额外担心 https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#输入
如果你遇到了没有结果的情况，需要查看你的代理是否足够稳定，本地网络是否能访问到谷歌。如果只使用翻译功能，可以不需要代理，使用这个方法直连 https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#翻译字幕

**Comment by findcoins** [comment]
> 我没有macOS环境，建议阅读 [agermanidis#144 (comment)](https://github.com/agermanidis/autosub/issues/144#issuecomment-534810438)
> 至于多声道音频，原版应该也会将其自动转换为单声道音频，不存在不支持的问题，不支持只是说API是不支持多声道的音频，但是autosub会帮你把输入转换成符合API要求的再上传，所以这个问题不需要额外担心 [https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#输入](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E8%BE%93%E5%85%A5)
> 如果你遇到了没有结果的情况，需要查看你的代理是否足够稳定，本地网络是否能访问到谷歌。如果只使用翻译功能，可以不需要代理，使用这个方法直连 [https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#翻译字幕](https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#%E7%BF%BB%E8%AF%91%E5%AD%97%E5%B9%95)

感谢回复。
我的代理使用的搬瓦工，终端代理用的privoxy。  在终端上尝试wget https://www.google.com 是可以测试通过的。 
原版有2个进度条，第一个迅速100%之后 第二个 也在其后缓慢的10% 20% 逐步完成了。并未报连接不上API服务器的错误。  但是转换出来的字幕文件就是0KB。。。
我还尝试了另外一个作者的autosub（他使用百度的API）也是从你的issue里面跟踪过去的。 安装到最后居然报语法错误。。。。

我需求的功能是语音转文字， 不是翻译。

**Comment by BingLingGroup** [comment]
@findcoins 你有没有试过先看本地分轴的功能能否正常使用，使用`-of regions`来仅输出时间轴来查看时间轴是否正常。

如果时间轴正常，那么你需要考虑你的音频音量是否足够大，建议先使用软件（如果Adobe Audition或者autosub内置的预处理）将音量标准化。

如果以上两种问题都被排除了，你也可以试试换成google cloud speech-to-text（0.5.4a新增的api支持），看看是不是免费API把你屏蔽了或者你网络不够稳定的情况——另外google cloud speech-to-text支持有损压缩`OGG_OPUS`格式，这种格式可以大幅减小体积和带宽使用。
`FLAC`码率一般在1Mbps左右，一个音频片段可能就有1MB，相比之下`OGG_OPUS`只有0.1Mbps左右，对于语音而言，质量损失较小，但可节省90%的体积。

如果没法换google cloud speech-to-text（譬如可能你没有国外支付方式无法绑定支付无法使用），你也可以试试单纯把语音识别请求的并发数量调到1（选项`-sc 1`），这样可以改善带宽使用情况。

至于应该使用什么vps才是稳定的网络，这个不是autosub相关的问题。另外既然你都租了vps，你完全可以直接在vps上操作，不需要本地走代理在本地操作，直接文件上传vps，在vps的终端上操作语音识别。
