### ISSUE TITLE
Can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by spinstein** [BingLingGroup/autosub#87]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
清晰并准确地描述问题。

**复现问题**
复现问题的步骤:
1. 你使用的命令行参数。
2. 一份完整的autosub命令行输出。你可以使用`Ctrl-A`和`Ctrl-C`去复制所有输出。推荐使用以下的代码块markdown语法。

```
```

3. 等等

**期待的行为**
清晰并准确地描述你本想做的事情。

**截图**
合适的话可以提供用以描述问题的截图。但是不推荐用截图来展示命令行输出，除非你真的认为这很有必要。

**操作环境（请提供以下完整数据）：**
 - 操作系统: [譬如 windows] windows 7
 - Python版本: [譬如 Python 2.7] 3.6.2
 - Autosub版本: [譬如 0.4.0] the newest one

**额外信息**（可选）
任何其他的能描述问题的信息。
```
C:\autosub-dev>autosub -i D:\FFOutput\01.mp3 -sapi gcsv1 -S en-US -bm all -F srt -sa C:\Users\Samuel\Downloads\3e46f5.json
Destination language not provided. Only performing speech recognition.
Speech language is the same as the Destination language. Only performing speech
recognition.

Convert source file to "C:\Users\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav" to g
et audio length and detect audio regions.
ffmpeg.exe -hide_banner -y -i "D:\FFOutput\01.mp3" -vn -ac 1 -ar 48000 "C:\Users
\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav"
Input #0, mp3, from 'D:\FFOutput\01.mp3':
  Metadata:
    encoder         : Lavf57.41.100
  Duration: 00:28:56.80, start: 0.025057, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 32 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav':
  Metadata:
    ISFT            : Lavf57.71.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16,
768 kb/s
    Metadata:
      encoder         : Lavc57.89.100 pcm_s16le
size=  162823kB time=00:28:56.77 bitrate= 768.0kbits/s speed= 262x
video:0kB audio:162823kB subtitle:0kB other streams:0kB global headers:0kB muxin
g overhead: 0.000047%

Use ffprobe to check conversion result.
ffprobe.exe C:\Users\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav -show_format -pre
tty -loglevel quiet
[FORMAT]
filename=C:\Users\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=0:28:56.778229
size=159.006870 Mibyte
bit_rate=768 Kbit/s
probe_score=99
TAG:encoder=Lavf57.71.100
[/FORMAT]

Detecting speech regions using Auditok.

"C:\Users\Samuel\AppData\Local\Temp\tmpyxuymcmx.wav" has been deleted.

Converting speech regions to short-term fragments.
Converting: 100% |#############################################| Time:  0:01:03
Set the GOOGLE_APPLICATION_CREDENTIALS given in the option "-sa"/"--service-acco
unt".

Sending short-term fragments to Google Cloud Speech V1P1Beta1 API and getting re
sult.
Speech-to-Text: N/A% |                                         | ETA:  --:--:--T
raceback (most recent call last):
  File "C:\Users\Samuel\AppData\Local\Programs\Python\Python36\Scripts\autosub-s
cript.py", line 11, in <module>
    load_entry_point('autosub==0.5.4a0', 'console_scripts', 'autosub')()
  File "c:\users\samuel\appdata\local\programs\python\python36\lib\site-packages
\autosub\__init__.py", line 145, in main
    styles_list=styles_list)
  File "c:\users\samuel\appdata\local\programs\python\python36\lib\site-packages
\autosub\cmdline_utils.py", line 1013, in audio_or_video_prcs
    is_keep=args.keep)
  File "c:\users\samuel\appdata\local\programs\python\python36\lib\site-packages
\autosub\core.py", line 288, in gcsv1_to_text
    transcript = task.get()
  File "c:\users\samuel\appdata\local\programs\python\python36\lib\multiprocessi
ng\pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing
.pool.ExceptionWithTraceback object at 0x0000000004960438>'. Reason: 'TypeError(
"can't pickle _thread.RLock objects",)'
Speech-to-Text: 100% |#########################################| Time:  0:00:14
```
Thank you for your code.

**Comment by BingLingGroup** [comment]
I test the gcsv1 API in Python 3.7.4 and it worked. Perhaps these multiprocessing codes can't run on Python 3.6.2.

I've already changed the codes to use the Google Cloud Speech-to-Text client under multiprocessing pool. (I comment these in the codes https://github.com/BingLingGroup/autosub/blob/dev/autosub/core.py#L279-L280) It just because the Google Cloud Speech-to-Text client package doesn't support multiprocessing, not autosub itself. So I have no idea how to modify codes to get further multiprocessing support when just import and use it as the document said unless someone know how to do it in a hack level.

Current solution to avoid any multiprocessing error as well as use the API under multiprocessing pool is to use API key instead of service account credentials because API key won't use that client package and the procedure is just the same as the free API which means using requests package to send HTTP requests and it's fully compatible with multiprocessing pool.

**Comment by spinstein** [comment]
> I test the gcsv1 API in Python 3.7.4 and it worked. Perhaps these multiprocessing codes can't run on Python 3.6.2.
> 
> I've already changed the codes to use the Google Cloud Speech-to-Text client under multiprocessing pool. (I comment these in the codes https://github.com/BingLingGroup/autosub/blob/dev/autosub/core.py#L279-L280) It just because the Google Cloud Speech-to-Text client package doesn't support multiprocessing, not autosub itself. So I have no idea how to modify codes to get further multiprocessing support when just import and use it as the document said unless someone know how to do it in a hack level.
> 
> Current solution to avoid any multiprocessing error as well as use the API under multiprocessing pool is to use API key instead of service account credentials because API key won't use that client package and the procedure is just the same as the free API which means using requests package to send requests and it's fully compatible with multiprocessing pool.

Thank you for you quick answer and your time.
That's very nice.
Have a good evening.

**Comment by BingLingGroup** [comment]
These are my Pycharm debug logs in Python 3.7.4(pipenv).
```
C:\Users\xxx\.virtualenvs\autosub-xxx\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 5825 --file C:/userfile/PycharmProjects/autosub/autosub/__main__.py -i C:\userfile\Video\autosub\test\temp.m4a -S zh -D en -bm all -sapi gcsv1 -sa C:\userfile\Video\autosub\test\xxx.json
pydev debugger: process 2376 is connecting

Connected to pydev debugger (build 192.5728.105)
警告：语音语言"zh"不在推荐的清单里面。用"-lsc"/"--list-speech-codes"选项运行来查看所有支持的语言。
现在匹配语言代码。
输入：            zh
分数高于：        90
匹配结果          分数（0-100）
cmn-hans-cn       100
cmn-hans-hk       96
使用langcodes来标准化结果。
改用"cmn-Hans-CN"。
翻译源语言未提供。改用语音语言。
警告：源语言"cmn-Hans-CN"不在推荐的清单里面。用 "-lsc"/"--list-translation-codes"选项运行来查看所有支持的语言。
现在匹配语言代码。
输入：            cmn-Hans-CN
分数高于：        90
匹配结果          分数（0-100）
zh-cn             100
改用"zh-cn"。

将源文件转换为"C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"来检测语音区域。
ffmpeg.exe -hide_banner -y -i "C:\userfile\Video\autosub\test\temp.m4a" -vn -ac 1 -ar 48000 "C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\userfile\Video\autosub\test\temp.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2019-02-14T04:02:57.000000Z
    encoder         : qaac 2.44, CoreAudioToolbox 7.9.9.3, AAC-LC Encoder, TVBR q127, Quality 96
    iTunSMPB        :  00000000 00000840 00000348 000000000029B878 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:01:02.07, start: 0.047891, bitrate: 88 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 86 kb/s (default)
    Metadata:
      creation_time   : 2019-02-14T04:02:57.000000Z
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    iTunSMPB        :  00000000 00000840 00000348 000000000029B878 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    ISFT            : Lavf58.29.100
    Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      creation_time   : 2019-02-14T04:02:57.000000Z
      encoder         : Lavc58.54.100 pcm_s16le
size=    5814kB time=00:01:02.01 bitrate= 768.0kbits/s speed= 676x    
video:0kB audio:5814kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001310%

使用ffprobe来检查转换结果。
ffprobe.exe C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav -show_format -pretty -loglevel quiet
[FORMAT]
filename=C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=0:01:02.019063
size=5.678089 Mibyte
bit_rate=768.010000 Kbit/s
probe_score=99
TAG:encoder=Lavf58.29.100
[/FORMAT]

使用Auditok检测语音区域。

"C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"已被删除。

转换中： N/A% |                                                    | ETA:  --:--:--
按照语音区域将音频转换为多个短语音片段。
转换中： N/A% |                                                    | ETA:  --:--:--
转换中：  18% |#########                                           | ETA:   0:00:04
转换中：  45% |#######################                             | ETA:   0:00:02
转换中： 100% |####################################################| Time:  0:00:02
设置选项"-sa"/"--service-account"提供的GOOGLE_APPLICATION_CREDENTIALS。

语音转文字中： N/A% |                                                 | ETA:  --:--:--
将短片段语音发送给Google Cloud Speech V1P1Beta1 API并得到识别结果。
语音转文字中：   9% |####                                             | ETA:   0:00:39
语音转文字中：  18% |########                                         | ETA:   0:00:22
语音转文字中：  27% |#############                                    | ETA:   0:00:17
语音转文字中：  45% |######################                           | ETA:   0:00:13
语音转文字中：  81% |########################################         | ETA:   0:00:02
语音转文字中：  90% |############################################     | ETA:   0:00:01
语音转文字中： 100% |#################################################| ETA:  00:00:00
语音转文字中： 100% |#################################################| Time:  0:00:16

从"zh-cn"翻译为"en"。
翻译中： N/A% |                                                    | ETA:  --:--:--
翻译中：   9% |####                                                | ETA:   0:00:19
翻译中： 100% |####################################################| Time:  0:00:01
目的语言字幕文件创建在了"C:\userfile\Video\autosub\test\temp.en.srt"。

做完了。

Process finished with exit code 0
```

**Comment by spinstein** [comment]
> These are my Pycharm debug logs in Python 3.7.4(pipenv).
> 
> ```
> C:\Users\xxx\.virtualenvs\autosub-xxx\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 5825 --file C:/userfile/PycharmProjects/autosub/autosub/__main__.py -i C:\userfile\Video\autosub\test\temp.m4a -S zh -D en -bm all -sapi gcsv1 -sa C:\userfile\Video\autosub\test\xxx.json
> pydev debugger: process 2376 is connecting
> 
> Connected to pydev debugger (build 192.5728.105)
> 警告：语音语言"zh"不在推荐的清单里面。用"-lsc"/"--list-speech-codes"选项运行来查看所有支持的语言。
> 现在匹配语言代码。
> 输入：            zh
> 分数高于：        90
> 匹配结果          分数（0-100）
> cmn-hans-cn       100
> cmn-hans-hk       96
> 使用langcodes来标准化结果。
> 改用"cmn-Hans-CN"。
> 翻译源语言未提供。改用语音语言。
> 警告：源语言"cmn-Hans-CN"不在推荐的清单里面。用 "-lsc"/"--list-translation-codes"选项运行来查看所有支持的语言。
> 现在匹配语言代码。
> 输入：            cmn-Hans-CN
> 分数高于：        90
> 匹配结果          分数（0-100）
> zh-cn             100
> 改用"zh-cn"。
> 
> 将源文件转换为"C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"来检测语音区域。
> ffmpeg.exe -hide_banner -y -i "C:\userfile\Video\autosub\test\temp.m4a" -vn -ac 1 -ar 48000 "C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\userfile\Video\autosub\test\temp.m4a':
>   Metadata:
>     major_brand     : M4A 
>     minor_version   : 0
>     compatible_brands: M4A mp42isom
>     creation_time   : 2019-02-14T04:02:57.000000Z
>     encoder         : qaac 2.44, CoreAudioToolbox 7.9.9.3, AAC-LC Encoder, TVBR q127, Quality 96
>     iTunSMPB        :  00000000 00000840 00000348 000000000029B878 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
>   Duration: 00:01:02.07, start: 0.047891, bitrate: 88 kb/s
>     Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 86 kb/s (default)
>     Metadata:
>       creation_time   : 2019-02-14T04:02:57.000000Z
> Stream mapping:
>   Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
> Press [q] to stop, [?] for help
> Output #0, wav, to 'C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav':
>   Metadata:
>     major_brand     : M4A 
>     minor_version   : 0
>     compatible_brands: M4A mp42isom
>     iTunSMPB        :  00000000 00000840 00000348 000000000029B878 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
>     ISFT            : Lavf58.29.100
>     Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
>     Metadata:
>       creation_time   : 2019-02-14T04:02:57.000000Z
>       encoder         : Lavc58.54.100 pcm_s16le
> size=    5814kB time=00:01:02.01 bitrate= 768.0kbits/s speed= 676x    
> video:0kB audio:5814kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001310%
> 
> 使用ffprobe来检查转换结果。
> ffprobe.exe C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav -show_format -pretty -loglevel quiet
> [FORMAT]
> filename=C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav
> nb_streams=1
> nb_programs=0
> format_name=wav
> format_long_name=WAV / WAVE (Waveform Audio)
> start_time=N/A
> duration=0:01:02.019063
> size=5.678089 Mibyte
> bit_rate=768.010000 Kbit/s
> probe_score=99
> TAG:encoder=Lavf58.29.100
> [/FORMAT]
> 
> 使用Auditok检测语音区域。
> 
> "C:\Users\xxx\AppData\Local\Temp\tmpfvt00p7v.wav"已被删除。
> 
> 转换中： N/A% |                                                    | ETA:  --:--:--
> 按照语音区域将音频转换为多个短语音片段。
> 转换中： N/A% |                                                    | ETA:  --:--:--
> 转换中：  18% |#########                                           | ETA:   0:00:04
> 转换中：  45% |#######################                             | ETA:   0:00:02
> 转换中： 100% |####################################################| Time:  0:00:02
> 设置选项"-sa"/"--service-account"提供的GOOGLE_APPLICATION_CREDENTIALS。
> 
> 语音转文字中： N/A% |                                                 | ETA:  --:--:--
> 将短片段语音发送给Google Cloud Speech V1P1Beta1 API并得到识别结果。
> 语音转文字中：   9% |####                                             | ETA:   0:00:39
> 语音转文字中：  18% |########                                         | ETA:   0:00:22
> 语音转文字中：  27% |#############                                    | ETA:   0:00:17
> 语音转文字中：  45% |######################                           | ETA:   0:00:13
> 语音转文字中：  81% |########################################         | ETA:   0:00:02
> 语音转文字中：  90% |############################################     | ETA:   0:00:01
> 语音转文字中： 100% |#################################################| ETA:  00:00:00
> 语音转文字中： 100% |#################################################| Time:  0:00:16
> 
> 从"zh-cn"翻译为"en"。
> 翻译中： N/A% |                                                    | ETA:  --:--:--
> 翻译中：   9% |####                                                | ETA:   0:00:19
> 翻译中： 100% |####################################################| Time:  0:00:01
> 目的语言字幕文件创建在了"C:\userfile\Video\autosub\test\temp.en.srt"。
> 
> 做完了。
> 
> Process finished with exit code 0
> ```

Wow. I will try update my python if the APIkey plan doesn't work.
Thank you for being so nice.

**Comment by spinstein** [comment]
C:\autosub-dev>autosub -i D:\FFOutput\01.mp3 -sapi gcsv1 -S en-US -bm all -F srt
 -skey *************hDi8
Destination language not provided. Only performing speech recognition.
Speech language is the same as the Destination language. Only performing speech
recognition.

Convert source file to "C:\Users\*******\AppData\Local\Temp\tmp9v8758sh.wav" to g
et audio length and detect audio regions.
ffmpeg.exe -hide_banner -y -i "D:\FFOutput\01.mp3" -vn -ac 1 -ar 48000 "C:\Users
\*******\AppData\Local\Temp\tmp9v8758sh.wav"
Input #0, mp3, from 'D:\FFOutput\01.mp3':
  Metadata:
    encoder         : Lavf57.41.100
  Duration: 00:28:56.80, start: 0.025057, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 32 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\*******\AppData\Local\Temp\tmp9v8758sh.wav':
  Metadata:
    ISFT            : Lavf57.71.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16,
768 kb/s
    Metadata:
      encoder         : Lavc57.89.100 pcm_s16le
size=  162823kB time=00:28:56.77 bitrate= 768.0kbits/s speed= 238x
video:0kB audio:162823kB subtitle:0kB other streams:0kB global headers:0kB muxin
g overhead: 0.000047%

Use ffprobe to check conversion result.
ffprobe.exe C:\Users\*******\AppData\Local\Temp\tmp9v8758sh.wav -show_format -pre
tty -loglevel quiet
[FORMAT]
filename=C:\Users\*******\AppData\Local\Temp\tmp9v8758sh.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=0:28:56.778229
size=159.006870 Mibyte
bit_rate=768 Kbit/s
probe_score=99
TAG:encoder=Lavf57.71.100
[/FORMAT]

Detecting speech regions using Auditok.

"C:\Users\*******\AppData\Local\Temp\tmp9v8758sh.wav" has been deleted.

Converting speech regions to short-term fragments.
Converting: 100% |#############################################| Time:  0:01:11
Use the API key given in the option "-skey"/"--speech-key".

Sending short-term fragments to Google Cloud Speech V1P1Beta1 API and getting re
sult.
Speech-to-Text: 100% |#########################################| Time:  0:00:13
Receive something unexpected:
{
  "error": {
    "code": 403,
    "message": "Cloud Speech-to-Text API has not been used in project 8464098962
32 before or it is disabled. Enable it by visiting https://console.developers.go
ogle.com/apis/api/speech.googleapis.com/overview?project=846409896232 then retry
. If you enabled this API recently, wait a few minutes for the action to propaga
te to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/speech.google
apis.com/overview?project=846409896232"
          }
        ]
      }
    ]
  }
}

Error: Speech-to-text failed.
All works done.

Actually, I have waited for almost 1 hour.
Maybe I should try it agin tomorrow.

**Comment by BingLingGroup** [comment]
@spinstein You can just use the free API. I test it and the result is almost the same. Google Cloud API is better when sending complex json request. I will add this feature in the next version.

**Comment by spinstein** [comment]
> @spinstein You can just use the free API. I test it and the result is almost the same. Google Cloud API is better when sending complex json request. I will add this feature in the next version.

Okay. I will try that. Thanks a million, again.
