### ISSUE TITLE
Run into fork error after running the script

### ISSUE THREAD

**Issue by fl41517** [BingLingGroup/autosub#93]
After I run the following cmd:
autosub -i dumpling\ in\ midtown.mp4 -SRC zh-TW -D zh-TW -S zh-TW

I get the following:
objc[12255]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[12255]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
objc[12254]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[12254]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

Please help :) I am using Mac, python2.7.

**Comment by BingLingGroup** [comment]
I google the output and find this solution.
https://github.com/darkskyapp/forecast-ruby/issues/13 
I don't have the macOS environment. So it's up to you to test whether it will work.

**Comment by BingLingGroup** [comment]
And please use the latest dev version instead of 0.5.5a currently due to this bug #89 
Similar issue: #65

**Comment by fl41517** [comment]
works like a charm! thanks!

**Comment by twardoch** [comment]
I can confirm that on macOS 10.14 Mojave with Python 3.7.7, autosub 0.5.6a0 works correctly when I call it like this: 

```
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES autosub -i file.mov -S en-us -sc 10
```

Perhaps you could include this briefly in the README?

**Comment by BingLingGroup** [comment]
@twardoch Ok.
At the same time I would consider some thread safe methods to do multiprocessing in python.

**Comment by twardoch** [comment]
oh sure, I thought that just as a hint until it's resolved

**Comment by twardoch** [comment]
My usage (and I'm sure many others) for autosub is for my own videos — the ones I make for YouTube. autosub is a great way to get the first draft that then only needs some corrections

**Comment by twardoch** [comment]
so I don't use it heavy-duty, and even just one thread is ok
