### ISSUE TITLE
Empty Results

### ISSUE THREAD

**Issue by Cineda** [BingLingGroup/autosub#94]
I have not used Autosubs for 1 month or so, and I have spent time reading the help docs but I don't see any issue similar to mine, hence my post.

**Describe the bug**
Running the program terminates at
`Speech-to-Text:   0% |                                                                                  | ETA:  0:27:05['{"result":[]}', '']`

**To Reproduce**
I ran command to get a Japanese video .mp4 with english subtitles.
` .\autosub.exe -i D:\path\path2\VIDEO-006.mp4 -S ja-jp -D en`

I have tried this too
` .\autosub.exe -i D:\path\path2\VIDEO-006.mp4 -S ja -D en`

**Expected behavior**
It should generate the English SRT.

**Environment (please complete the following information):**
 - Windows 10 
 - Python 3.8.0
 - Autosub 0.5.5-alpha

**Full log**
```
Source language not provided. Use Speech language instead.
Warning: Source language "ja-jp" not supported. Run with "-lsc"/"--list-translation-codes" to see all supported languages.
Now match lang codes.
Input:            ja-jp
Score above:      90
Match result      Score (0-100)
ja                100
Use "ja" instead.

Convert source file to "C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav" to detect audio regions.
ffmpeg.exe -hide_banner -y -i "D:\RipJar\sync4\ZIZG-006.mp4" -vn -ac 1 -ar 48000 "C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\RipJar\sync4\ZIZG-006.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2014-12-25T04:13:46.000000Z
    encoder         : Lavf54.59.106
  Duration: 03:00:11.63, start: 0.000000, bitrate: 1329 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 720x404 [SAR 254:255 DAR 3048:1717], 1192 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2014-12-25T04:13:46.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2014-12-25T04:13:46.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf58.29.100
    Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      creation_time   : 2014-12-25T04:13:46.000000Z
      handler_name    : SoundHandler
      encoder         : Lavc58.54.100 pcm_s16le
size= 1013588kB time=03:00:11.60 bitrate= 768.0kbits/s speed=13.7x
video:0kB audio:1013588kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000008%

Use ffprobe to check conversion result.
ffprobe.exe C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav -show_format -pretty -loglevel quiet
[FORMAT]
filename=C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=3:00:11.605333
size=989.832106 Mibyte
bit_rate=768 Kbit/s
probe_score=99
TAG:encoder=Lavf58.29.100
[/FORMAT]

Conversion complete.
Use Auditok to detect speech regions.

"C:\Users\Username\AppData\Local\Temp\tmpw2wvc24o.wav" has been deleted.

Converting speech regions to short-term fragments.
Converting: 100% |######################################################################################| Time: 0:09:01

Sending short-term fragments to Google Speech V2 API and getting result.
Speech-to-Text:   0% |                                                                                  | ETA:  0:27:05['{"result":[]}', '']
```

**Comment by BingLingGroup** [comment]
Perhaps you forget to search the issue. #89 

> Make sure you have read the readme, searched and read the issues related to yours. 

After all it's a bug. I will fix this in the future release. Currently you can install the latest dev version to fix this. I think it's the same bug as the #89.

**Comment by Cineda** [comment]
My apologies, thanks for replying! 👍

**Comment by BingLingGroup** [comment]
@Cineda So, are your problem solved?

**Comment by Cineda** [comment]
@BingLingGroup I am unsure, but it seems like its still not working with the same error, but with better verbose of progress bar.

I removed my existing Autosub and ran
```
choco install git python2 curl ffmpeg -y
curl `https://bootstrap.pypa.io/get-pip.py` -o get-pip.py
python get-pip.py
pip install git+https://github.com/BingLingGroup/autosub.git@alpha ffmpeg-normalize
```
which I believe is same as dev branch? 


Then I tried on another with same arguments. File is about 2-3 hours in length, Japanese audio, but I don't think that matters.

Full logs
--------


`
PS C:\Users\Username\Dropbox\Me\autosub> autosub -i D:\folder\VIDEO-9914.mp4 -S ja -D en
Warning: Speech language "ja" not recommended. Run with "-lsc"/"--list-speech-codes" to see all supported languages.
Source language not provided. Use Speech language instead.

Convert source file to "c:\users\Username\appdata\local\temp\tmppsvb6d.wav" to detect audio regions.
C:\ProgramData\chocolatey\bin\ffmpeg.exe -hide_banner -y -i "D:\folder\VIDEO-9914.mp4" -vn -ac 1 -ar 48000 "c:\users\Username\appdata\local\temp\tmppsvb6d.wav"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\folder\VIDEO-9914.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.38.100
  Duration: 02:10:17.20, start: 0.000000, bitrate: 5998 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 5733 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'c:\users\Username\appdata\local\temp\tmppsvb6d.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf58.29.100
    Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, mono, s16, 768 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc58.54.100 pcm_s16le
size=  732862kB time=02:10:17.19 bitrate= 768.0kbits/s speed=2.72x
video:0kB audio:732862kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000010%

Use ffprobe to check conversion result.
C:\ProgramData\chocolatey\bin\ffprobe.exe c:\users\Username\appdata\local\temp\tmppsvb6d.wav -show_format -pretty -loglevel quiet
[FORMAT]
filename=c:\users\Username\appdata\local\temp\tmppsvb6d.wav
nb_streams=1
nb_programs=0
format_name=wav
format_long_name=WAV / WAVE (Waveform Audio)
start_time=N/A
duration=2:10:17.194667
size=715.685621 Mibyte
bit_rate=768 Kbit/s
probe_score=99
TAG:encoder=Lavf58.29.100
[/FORMAT]

Conversion complete.
Use Auditok to detect speech regions.

"c:\users\Username\appdata\local\temp\tmppsvb6d.wav" has been deleted.

Converting speech regions to short-term fragments.
Converting: N/A% |                                                                                     | ETA:  --:--:--
Converting: N/A% |                                                                                     | ETA:  --:--:--
Converting:   0% |                                                                                     | ETA:   4:47:11
Converting:   0% |                                                                                     | ETA:   1:32:10
Converting:   0% |                                                                                     | ETA:   0:40:31
Converting:   0% |                                                                                     | ETA:   0:40:45
Converting:   0% |                                                                                     | ETA:   0:41:41
Converting:   0% |                                                                                     | ETA:   0:38:00
Converting:   0% |                                                                                     | ETA:   0:39:15
Converting:   0% |                                                                                     | ETA:   0:33:11
Converting:   0% |                                                                                     | ETA:   0:32:16
Converting:   0% |                                                                                     | ETA:   0:32:46
Converting:   1% |                                                                                     | ETA:   0:29:08
Converting:   1% |#                                                                                    | ETA:   0:28:57
Converting:   1% |#                                                                                    | ETA:   0:32:00
Converting:   1% |#                                                                                    | ETA:   0:27:12
Converting:   1% |#                                                                                    | ETA:   0:27:32
Converting:   1% |#                                                                                    | ETA:   0:26:53
Converting:   1% |#                                                                                    | ETA:   0:29:06
Converting:   1% |#                                                                                    | ETA:   0:26:23
Converting:   1% |#                                                                                    | ETA:   0:27:04
Converting:   1% |#                                                                                    | ETA:   0:27:13
Converting:   2% |#                                                                                    | ETA:   0:26:26
Converting:   2% |#                                                                                    | ETA:   0:27:15
Converting:   2% |#                                                                                    | ETA:   0:25:19
Converting:   2% |##                                                                                   | ETA:   0:26:18
Converting:   2% |##                                                                                   | ETA:   0:25:40
Converting:   2% |##                                                                                   | ETA:   0:25:39
Converting:   2% |##                                                                                   | ETA:   0:25:16
Converting:   2% |##                                                                                   | ETA:   0:25:26
Converting:   2% |##                                                                                   | ETA:   0:24:49
Converting:   2% |##                                                                                   | ETA:   0:25:17
Converting:   2% |##                                                                                   | ETA:   0:24:58
Converting:   2% |##                                                                                   | ETA:   0:24:45
Converting:   2% |##                                                                                   | ETA:   0:25:38
Converting:   3% |##                                                                                   | ETA:   0:25:05
Converting:   3% |##                                                                                   | ETA:   0:25:07
Converting:   3% |##                                                                                   | ETA:   0:25:20
Converting:   3% |##                                                                                   | ETA:   0:25:37
Converting:   3% |##                                                                                   | ETA:   0:25:23
Converting:   3% |##                                                                                   | ETA:   0:24:58
Converting:   3% |##                                                                                   | ETA:   0:25:14
Converting:   3% |###                                                                                  | ETA:   0:25:29
Converting:   3% |###                                                                                  | ETA:   0:25:16
Converting:   3% |###                                                                                  | ETA:   0:24:11
Converting:   3% |###                                                                                  | ETA:   0:24:13
Converting:   3% |###                                                                                  | ETA:   0:24:14
Converting:   4% |###                                                                                  | ETA:   0:23:29
Converting:   4% |###                                                                                  | ETA:   0:23:42
Converting:   4% |###                                                                                  | ETA:   0:23:40
Converting:   4% |###                                                                                  | ETA:   0:24:28
Converting:   4% |###                                                                                  | ETA:   0:23:41
Converting:   4% |###                                                                                  | ETA:   0:24:01
Converting:   4% |###                                                                                  | ETA:   0:23:51
Converting:   4% |###                                                                                  | ETA:   0:23:56
Converting:   4% |###                                                                                  | ETA:   0:24:40
Converting:   4% |####                                                                                 | ETA:   0:24:01
Converting:   4% |####                                                                                 | ETA:   0:23:47
Converting:   4% |####                                                                                 | ETA:   0:24:22
Converting:   4% |####                                                                                 | ETA:   0:24:05
Converting:   5% |####                                                                                 | ETA:   0:24:27
Converting:   5% |####                                                                                 | ETA:   0:24:36
Converting:   5% |####                                                                                 | ETA:   0:24:56
Converting:   5% |####                                                                                 | ETA:   0:24:23
Converting:   5% |####                                                                                 | ETA:   0:24:19
Converting:   5% |####                                                                                 | ETA:   0:24:21
Converting:   5% |####                                                                                 | ETA:   0:24:45
Converting:   5% |####                                                                                 | ETA:   0:24:20
Converting:   5% |####                                                                                 | ETA:   0:24:27
Converting:   5% |####                                                                                 | ETA:   0:24:47
Converting:   5% |####                                                                                 | ETA:   0:24:30
Converting:   5% |#####                                                                                | ETA:   0:24:25
Converting:   5% |#####                                                                                | ETA:   0:24:15
Converting:   6% |#####                                                                                | ETA:   0:24:36
Converting:   6% |#####                                                                                | ETA:   0:24:20
Converting:   6% |#####                                                                                | ETA:   0:24:01
Converting:   6% |#####                                                                                | ETA:   0:23:52
Converting:   6% |#####                                                                                | ETA:   0:23:39
Converting:   8% |######                                                                               | ETA:   0:22:44
Converting:   8% |######                                                                               | ETA:   0:22:54
Converting:   8% |#######                                                                              | ETA:   0:22:39
Converting:   8% |#######                                                                              | ETA:   0:22:36
Converting:   8% |#######                                                                              | ETA:   0:22:41
Converting:   8% |#######                                                                              | ETA:   0:22:15
Converting:   8% |#######                                                                              | ETA:   0:22:21
Converting:   8% |#######                                                                              | ETA:   0:22:42
Converting:   9% |#######                                                                              | ETA:   0:22:23
Converting:   9% |#######                                                                              | ETA:   0:21:55
Converting:   9% |#######                                                                              | ETA:   0:22:06
Converting:   9% |########                                                                             | ETA:   0:21:46
Converting:   9% |########                                                                             | ETA:   0:21:43
Converting:   9% |########                                                                             | ETA:   0:21:59
Converting:   9% |########                                                                             | ETA:   0:21:57
Converting:  16% |#############                                                                        | ETA:   0:18:18
Converting:  16% |##############                                                                       | ETA:   0:18:32
Converting:  16% |##############                                                                       | ETA:   0:18:18
Converting:  16% |##############                                                                       | ETA:   0:18:11
Converting:  17% |##############                                                                       | ETA:   0:18:12
Converting:  17% |##############                                                                       | ETA:   0:18:15
Converting:  17% |##############                                                                       | ETA:   0:18:06
Converting:  17% |##############                                                                       | ETA:   0:18:10
Converting:  17% |##############                                                                       | ETA:   0:18:05
Converting:  17% |##############                                                                       | ETA:   0:18:05
Converting:  17% |##############                                                                       | ETA:   0:18:04
Converting:  17% |###############                                                                      | ETA:   0:17:53
Converting:  17% |###############                                                                      | ETA:   0:17:54
Converting:  17% |###############                                                                      | ETA:   0:17:55
Converting:  17% |###############                                                                      | ETA:   0:17:52
Converting:  17% |###############                                                                      | ETA:   0:17:49
Converting:  17% |###############                                                                      | ETA:   0:17:59
Converting:  18% |###############                                                                      | ETA:   0:18:02
Converting:  18% |###############                                                                      | ETA:   0:18:01
Converting:  18% |###############                                                                      | ETA:   0:17:59
Converting:  18% |###############                                                                      | ETA:   0:18:01
Converting:  18% |###############                                                                      | ETA:   0:18:08
Converting:  18% |###############                                                                      | ETA:   0:17:52
Converting:  18% |###############                                                                      | ETA:   0:17:59
Converting:  18% |###############                                                                      | ETA:   0:17:59
Converting:  18% |###############                                                                      | ETA:   0:17:56
Converting:  18% |################                                                                     | ETA:   0:18:01
Converting:  18% |################                                                                     | ETA:   0:18:03
Converting:  19% |################                                                                     | ETA:   0:17:59
Converting:  19% |################                                                                     | ETA:   0:17:57
Converting:  24% |####################                                                                 | ETA:   0:16:19
Converting:  24% |####################                                                                 | ETA:   0:16:14
Converting:  24% |####################                                                                 | ETA:   0:16:20
Converting:  24% |#####################                                                                | ETA:   0:16:06
Converting:  24% |#####################                                                                | ETA:   0:16:04
Converting:  27% |#######################                                                              | ETA:   0:15:14
Converting:  27% |#######################                                                              | ETA:   0:15:08
Converting:  47% |########################################                                             | ETA:   0:10:04
Converting:  47% |########################################                                             | ETA:   0:10:01
Converting:  47% |########################################                                             | ETA:   0:10:01
Converting:  47% |########################################                                             | ETA:   0:10:00
Converting:  48% |########################################                                             | ETA:   0:09:59
Converting:  48% |########################################                                             | ETA:   0:09:59
Converting:  49% |##########################################                                           | ETA:   0:09:33
Converting:  52% |############################################                                         | ETA:   0:08:55
Converting:  52% |############################################                                         | ETA:   0:08:53
Converting:  52% |############################################                                         | ETA:   0:08:50
Converting:  52% |############################################                                         | ETA:   0:08:46
Converting:  52% |############################################                                         | ETA:   0:08:48
Converting:  54% |#############################################                                        | ETA:   0:08:33
Converting:  54% |##############################################                                       | ETA:   0:08:32
Converting:  54% |##############################################                                       | ETA:   0:08:31
Converting:  54% |##############################################                                       | ETA:   0:08:31
Converting:  54% |##############################################                                       | ETA:   0:08:31
Converting:  54% |##############################################                                       | ETA:   0:08:31
Converting:  54% |##############################################                                       | ETA:   0:08:31
Converting:  54% |##############################################                                       | ETA:   0:08:29
Converting:  56% |################################################                                     | ETA:   0:08:01
Converting:  57% |################################################                                     | ETA:   0:08:01
Converting:  57% |################################################                                     | ETA:   0:07:59
Converting:  57% |################################################                                     | ETA:   0:08:00
Converting:  57% |################################################                                     | ETA:   0:07:57
Converting:  57% |################################################                                     | ETA:   0:07:57
Converting:  57% |################################################                                     | ETA:   0:07:57
Converting:  57% |################################################                                     | ETA:   0:07:56
Converting:  57% |#################################################                                    | ETA:   0:07:54
Converting:  57% |#################################################                                    | ETA:   0:07:54
Converting:  57% |#################################################                                    | ETA:   0:07:50
Converting:  58% |#################################################                                    | ETA:   0:07:50
Converting:  58% |#################################################                                    | ETA:   0:07:50
Converting:  58% |#################################################                                    | ETA:   0:07:49
Converting:  58% |#################################################                                    | ETA:   0:07:49
Converting:  58% |#################################################                                    | ETA:   0:07:49
Converting:  58% |#################################################                                    | ETA:   0:07:50
Converting:  58% |#################################################                                    | ETA:   0:07:46
Converting:  70% |###########################################################                          | ETA:   0:05:36
Converting:  70% |###########################################################                          | ETA:   0:05:35
Converting:  70% |###########################################################                          | ETA:   0:05:33
Converting:  70% |###########################################################                          | ETA:   0:05:30
Converting:  70% |###########################################################                          | ETA:   0:05:29
Converting:  70% |###########################################################                          | ETA:   0:05:28
Converting:  70% |############################################################                         | ETA:   0:05:28
Converting:  70% |############################################################                         | ETA:   0:05:25
Converting:  70% |############################################################                         | ETA:   0:05:25
Converting:  70% |############################################################                         | ETA:   0:05:23
Converting:  71% |############################################################                         | ETA:   0:05:22
Converting:  71% |############################################################                         | ETA:   0:05:22
Converting:  71% |############################################################                         | ETA:   0:05:21
Converting:  73% |##############################################################                       | ETA:   0:04:52
Converting:  73% |##############################################################                       | ETA:   0:04:51
Converting:  75% |################################################################                     | ETA:   0:04:28
Converting:  75% |################################################################                     | ETA:   0:04:27
Converting:  75% |################################################################                     | ETA:   0:04:26
Converting:  75% |################################################################                     | ETA:   0:04:25
Converting:  75% |################################################################                     | ETA:   0:04:24
Converting:  75% |################################################################                     | ETA:   0:04:23
Converting:  75% |################################################################                     | ETA:   0:04:23
Converting:  75% |################################################################                     | ETA:   0:04:22
Converting:  75% |################################################################                     | ETA:   0:04:20
Converting:  76% |################################################################                     | ETA:   0:04:20
Converting:  76% |################################################################                     | ETA:   0:04:18
Converting:  76% |################################################################                     | ETA:   0:04:18
Converting:  76% |################################################################                     | ETA:   0:04:18
Converting:  76% |################################################################                     | ETA:   0:04:16
Converting:  86% |#########################################################################            | ETA:   0:02:20
Converting:  86% |#########################################################################            | ETA:   0:02:19
Converting:  86% |#########################################################################            | ETA:   0:02:18
Converting:  86% |#########################################################################            | ETA:   0:02:18
Converting:  86% |#########################################################################            | ETA:   0:02:16
Converting:  86% |#########################################################################            | ETA:   0:02:15
Converting:  87% |#########################################################################            | ETA:   0:02:15
Converting:  87% |##########################################################################           | ETA:   0:02:14
Converting:  87% |##########################################################################           | ETA:   0:02:14
Converting:  87% |##########################################################################           | ETA:   0:02:14
Converting:  87% |##########################################################################           | ETA:   0:02:11
Converting:  87% |##########################################################################           | ETA:   0:02:10
Converting:  87% |##########################################################################           | ETA:   0:02:10
Converting:  87% |##########################################################################           | ETA:   0:02:09
Converting:  87% |##########################################################################           | ETA:   0:02:08
Converting:  87% |##########################################################################           | ETA:   0:02:07
Converting:  87% |##########################################################################           | ETA:   0:02:06
Converting:  87% |##########################################################################           | ETA:   0:02:06
Converting:  89% |############################################################################         | ETA:   0:01:48
Converting:  89% |############################################################################         | ETA:   0:01:46
Converting:  89% |############################################################################         | ETA:   0:01:45
Converting:  93% |###############################################################################      | ETA:   0:01:05
Converting:  93% |###############################################################################      | ETA:   0:01:04
Converting:  93% |###############################################################################      | ETA:   0:01:03
Converting:  93% |###############################################################################      | ETA:   0:01:02
Converting:  99% |#################################################################################### | ETA:   0:00:04
Converting:  99% |#################################################################################### | ETA:   0:00:03
Converting:  99% |#################################################################################### | ETA:   0:00:03
Converting:  99% |#################################################################################### | ETA:   0:00:02
Converting:  99% |#################################################################################### | ETA:   0:00:01
Converting:  99% |#################################################################################### | ETA:   0:00:01
Converting:  99% |#################################################################################### | ETA:   0:00:00
Converting: 100% |#####################################################################################| Time:  0:16:53

Sending short-term fragments to Google Speech V2 API and getting result.
Speech-to-Text: N/A% |                                                                                 | ETA:  --:--:--
[u'{"result":[]}', u'']
PS C:\Users\Username\Dropbox\Me\autosub>

**Comment by BingLingGroup** [comment]
@Cineda Sorry, but...no. 
This is an alpha branch installation command.
```
pip install git+https://github.com/BingLingGroup/autosub.git@alpha
```
And this is the dev branch installation command.
```
pip install git+https://github.com/BingLingGroup/autosub.git@dev
```

If you want to ignore the empty regions before sending it to the API, please use `-sml`. Because this is a known issue for the API. When sending some too short audio fragments to it, it will send back the empty responses, not just empty results. This is why this program raise the exception. I fix this in the latest dev version but I don't fix the default option for auditok which is used to generate the regions and sometimes it generates some too short regions due to the max region length limit but in default condition the min region length limit wouldn't be that strict so you need to use `-sml` to avoid this. I will fix this in the next version by changing the default `-sml` into `-nsml`. 

If you want to delete the empty regions after receiving the result from the API, please use `-der`. This will detect those with empty response or empty result subtitles's lines and remove them.

**Comment by Cineda** [comment]
Thanks for replying, I assumed alpha == dev, I was wrong.

Anyways here's the latest run with the arguments you suggested:

```
pip install git+https://github.com/BingLingGroup/autosub.git@dev
autosub -i D:\folder\VIDEO-4234.mp4 -S ja -D en -sml -der
```

Here's the full log, which is super long. I pasted on Pastebin instead.
https://pastebin.com/Gk9L1fWt

**Comment by BingLingGroup** [comment]
@Cineda Sorry, but I think the version you have installed is still not the dev version. You need to uninstall the old version first. Because they have the same version number, pip doesn't overwrite the old ones. You need to run
 ```
pip install git+https://github.com/BingLingGroup/autosub.git@dev --upgrade
```
or 
```
pip uninstall autosub
pip install git+https://github.com/BingLingGroup/autosub.git@dev
```

**Comment by Cineda** [comment]
Ah my bad. It works now that I have the dev branch installed. 
Thank you! :) 👍
