### ISSUE TITLE
在使用-D 翻译时,提供-D cmn-hans-cn报错(但cmn-hans-cn是-lsc语言列表中提供的)

### ISSUE THREAD

**Issue by a690089735** [BingLingGroup/autosub#97]
在使用-D 翻译时,提供-D cmn-hans-cn报错(但cmn-hans-cn是-lsc语言列表中提供的)
使用-D zh-CN 可以通过.....但-lsc中没有这个语言代码..

**Comment by BingLingGroup** [comment]
建议先仔细阅读readme

https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#语音转文字翻译语言支持

> 语音转文字的语言代码和翻译的语言代码是不一样的，因为这俩API并不相同。当然啦，这些语言代码的格式是谷歌化的，和iso标准不一样，会导致用户使用时很迷惑。
>为了解决这个问题，autosub使用langcodes来检测输入的语言代码并在语言代码清单中找到与其最匹配的一项来使用。默认并不会启用这个功能。需要在不同的阶段都启动这个功能，可以使用选项-bm all。
>为了手动匹配或者查看本程序允许使用的语言代码，你可以通过输入参数-lsc/--list-speech-to-text-codes以及-ltc/--list-translation-codes来获得。或者你也可以打开constants.py来查看。
