### ISSUE TITLE
自适应分割音频为单句的功能(替换掉强制的6秒)

### ISSUE THREAD

**Issue by a690089735** [BingLingGroup/autosub#98]
均分的语音长度(强制6秒和10秒),大大降低了语音识别准确性和翻译准确性.
请求添加自适应分割音频为单句的功能(替换掉强制的6秒),类似speechlogger,自适应分割音频在google翻译加持下,翻译的准确性会变得十分可接受.

相关可能有帮助的文章:
https://blog.csdn.net/wblgers1234/article/details/77103444
https://github.com/wblgers/py_speech_seg

**Comment by BingLingGroup** [comment]
这并不是均分，6秒和10秒是最大长度限制，你需要根据你的音频音量大小，来调整`-et`和`-mxcs`的值，Auditok是基于 [Acoustic Activity Detection](https://auditok.readthedocs.io/en/latest/apitutorial.html) 而非神经网络的方法。当然，如果你觉得神经网络的方法更好，请提pull request。

另外强烈建议你先仔细阅读一下readme再评价，同时建议你提供一份BIC方法比Auditok更准的测试结果。

**Comment by a690089735** [comment]
谢谢解释。现在我明白了，这是因为我没有修改-et的参数，而默认的et参数不适合所有。因为没看懂auditok中对energy_threshold我做了一些测试，-et参数有点太灵活了，但总体看来越小越敏感，更容易生成很长的音频，值越大越宽容，甚至可能导致输出为空字幕。
关于bic与auditok方法的测试，抱歉我没有能力，我很笨拙。我觉得auditok很好。我只是将随处看见的文章贴了进来，似乎有一些不负责任。

**Comment by a690089735** [comment]
谢谢解释。现在我明白了，这是因为我没有修改-et的参数，而默认的et参数不适合所有。因为没看懂auditok中对energy_threshold的解释（好像只提到了应该谨慎使用），我为自己做了一些测试，-et参数有点太灵活了，但总体看来越小越敏感，更容易生成很长的音频，值越大越宽容，甚至可能导致输出为空字幕。
关于bic与auditok方法的测试，抱歉我没有能力，我很笨拙。我觉得auditok很好。我只是将随处看见的文章贴了进来，似乎有一些不负责任。
