### ISSUE TITLE
提示临时文件已被删除

### ISSUE THREAD

**Issue by ljq29** [BingLingGroup/autosub#99]
**确保你已经看过 readme，也搜索并阅读过和你遇到的情况相关的问题。否则会被认为是重复的并被立刻关闭。**

**描述问题**
使用命令 
-i "E:\20-03-21-16-35-24.mp4" -S zh-CN -of src
转换视频，提示如

**复现问题**
复现问题的步骤:
双击打开autosub，输入如上命令

```
-i "E:\20-03-21-16-35-24.mp4" -S zh-CN -of src
```

3. 截图：
http://v2ex.antior.cn/temp/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200328084147.png

**操作环境（请提供以下完整数据）：**

- 操作系统:windows 10
- Python版本: python 3.7.3
- Autosub版本: 0.4.1-alpha和0.5.4-alpha Nuitka windows都有此问题

**Comment by BingLingGroup** [comment]
错误信息实际上是Auditok无法检测到语音区域，请检查你的音频文件的音量大小，参考此解决方法 https://github.com/BingLingGroup/autosub/blob/dev/docs/README.zh-Hans.md#准确性

**Comment by BingLingGroup** [comment]
太长时间没回复，先关闭了，关闭后也可以留言。
